// This file was autogenerated by GLCSGen on 11/4/2013 8:49:49 AM
// Original copyright from gl.xml:
// 
// Copyright (c) 2013 The Khronos Group Inc.
// 
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and/or associated documentation files (the
// "Materials"), to deal in the Materials without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Materials, and to
// permit persons to whom the Materials are furnished to do so, subject to
// the following conditions:
// 
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Materials.
// 
// THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.
// 
// ------------------------------------------------------------------------
// 
// This file, gl.xml, is the OpenGL and OpenGL API Registry. The older
// ".spec" file format has been retired and will no longer be updated with
// new extensions and API versions. The canonical version of the registry,
// together with documentation, schema, and Python generator scripts used
// to generate C header files for OpenGL and OpenGL ES, can always be found
// in the Khronos Registry at
//         http://www.opengl.org/registry/
//     

using System;
using System.Reflection;
using System.Runtime.InteropServices;

namespace OpenGL
{
    public static class GLES10
    {
        #region Enums
        public static uint GL_VERSION_ES_CL_1_0 = 1;
        public static uint GL_VERSION_ES_CM_1_1 = 1;
        public static uint GL_VERSION_ES_CL_1_1 = 1;
        public static uint GL_DEPTH_BUFFER_BIT = 0x00000100;
        public static uint GL_STENCIL_BUFFER_BIT = 0x00000400;
        public static uint GL_COLOR_BUFFER_BIT = 0x00004000;
        public static uint GL_FALSE = 0;
        public static uint GL_TRUE = 1;
        public static uint GL_POINTS = 0x0000;
        public static uint GL_LINES = 0x0001;
        public static uint GL_LINE_LOOP = 0x0002;
        public static uint GL_LINE_STRIP = 0x0003;
        public static uint GL_TRIANGLES = 0x0004;
        public static uint GL_TRIANGLE_STRIP = 0x0005;
        public static uint GL_TRIANGLE_FAN = 0x0006;
        public static uint GL_NEVER = 0x0200;
        public static uint GL_LESS = 0x0201;
        public static uint GL_EQUAL = 0x0202;
        public static uint GL_LEQUAL = 0x0203;
        public static uint GL_GREATER = 0x0204;
        public static uint GL_NOTEQUAL = 0x0205;
        public static uint GL_GEQUAL = 0x0206;
        public static uint GL_ALWAYS = 0x0207;
        public static uint GL_ZERO = 0;
        public static uint GL_ONE = 1;
        public static uint GL_SRC_COLOR = 0x0300;
        public static uint GL_ONE_MINUS_SRC_COLOR = 0x0301;
        public static uint GL_SRC_ALPHA = 0x0302;
        public static uint GL_ONE_MINUS_SRC_ALPHA = 0x0303;
        public static uint GL_DST_ALPHA = 0x0304;
        public static uint GL_ONE_MINUS_DST_ALPHA = 0x0305;
        public static uint GL_DST_COLOR = 0x0306;
        public static uint GL_ONE_MINUS_DST_COLOR = 0x0307;
        public static uint GL_SRC_ALPHA_SATURATE = 0x0308;
        public static uint GL_CLIP_PLANE0 = 0x3000;
        public static uint GL_CLIP_PLANE1 = 0x3001;
        public static uint GL_CLIP_PLANE2 = 0x3002;
        public static uint GL_CLIP_PLANE3 = 0x3003;
        public static uint GL_CLIP_PLANE4 = 0x3004;
        public static uint GL_CLIP_PLANE5 = 0x3005;
        public static uint GL_FRONT = 0x0404;
        public static uint GL_BACK = 0x0405;
        public static uint GL_FRONT_AND_BACK = 0x0408;
        public static uint GL_FOG = 0x0B60;
        public static uint GL_LIGHTING = 0x0B50;
        public static uint GL_TEXTURE_2D = 0x0DE1;
        public static uint GL_CULL_FACE = 0x0B44;
        public static uint GL_ALPHA_TEST = 0x0BC0;
        public static uint GL_BLEND = 0x0BE2;
        public static uint GL_COLOR_LOGIC_OP = 0x0BF2;
        public static uint GL_DITHER = 0x0BD0;
        public static uint GL_STENCIL_TEST = 0x0B90;
        public static uint GL_DEPTH_TEST = 0x0B71;
        public static uint GL_POINT_SMOOTH = 0x0B10;
        public static uint GL_LINE_SMOOTH = 0x0B20;
        public static uint GL_SCISSOR_TEST = 0x0C11;
        public static uint GL_COLOR_MATERIAL = 0x0B57;
        public static uint GL_NORMALIZE = 0x0BA1;
        public static uint GL_RESCALE_NORMAL = 0x803A;
        public static uint GL_VERTEX_ARRAY = 0x8074;
        public static uint GL_NORMAL_ARRAY = 0x8075;
        public static uint GL_COLOR_ARRAY = 0x8076;
        public static uint GL_TEXTURE_COORD_ARRAY = 0x8078;
        public static uint GL_MULTISAMPLE = 0x809D;
        public static uint GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
        public static uint GL_SAMPLE_ALPHA_TO_ONE = 0x809F;
        public static uint GL_SAMPLE_COVERAGE = 0x80A0;
        public static uint GL_NO_ERROR = 0;
        public static uint GL_INVALID_ENUM = 0x0500;
        public static uint GL_INVALID_VALUE = 0x0501;
        public static uint GL_INVALID_OPERATION = 0x0502;
        public static uint GL_STACK_OVERFLOW = 0x0503;
        public static uint GL_STACK_UNDERFLOW = 0x0504;
        public static uint GL_OUT_OF_MEMORY = 0x0505;
        public static uint GL_EXP = 0x0800;
        public static uint GL_EXP2 = 0x0801;
        public static uint GL_FOG_DENSITY = 0x0B62;
        public static uint GL_FOG_START = 0x0B63;
        public static uint GL_FOG_END = 0x0B64;
        public static uint GL_FOG_MODE = 0x0B65;
        public static uint GL_FOG_COLOR = 0x0B66;
        public static uint GL_CW = 0x0900;
        public static uint GL_CCW = 0x0901;
        public static uint GL_CURRENT_COLOR = 0x0B00;
        public static uint GL_CURRENT_NORMAL = 0x0B02;
        public static uint GL_CURRENT_TEXTURE_COORDS = 0x0B03;
        public static uint GL_POINT_SIZE = 0x0B11;
        public static uint GL_POINT_SIZE_MIN = 0x8126;
        public static uint GL_POINT_SIZE_MAX = 0x8127;
        public static uint GL_POINT_FADE_THRESHOLD_SIZE = 0x8128;
        public static uint GL_POINT_DISTANCE_ATTENUATION = 0x8129;
        public static uint GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12;
        public static uint GL_LINE_WIDTH = 0x0B21;
        public static uint GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22;
        public static uint GL_ALIASED_POINT_SIZE_RANGE = 0x846D;
        public static uint GL_ALIASED_LINE_WIDTH_RANGE = 0x846E;
        public static uint GL_CULL_FACE_MODE = 0x0B45;
        public static uint GL_FRONT_FACE = 0x0B46;
        public static uint GL_SHADE_MODEL = 0x0B54;
        public static uint GL_DEPTH_RANGE = 0x0B70;
        public static uint GL_DEPTH_WRITEMASK = 0x0B72;
        public static uint GL_DEPTH_CLEAR_VALUE = 0x0B73;
        public static uint GL_DEPTH_FUNC = 0x0B74;
        public static uint GL_STENCIL_CLEAR_VALUE = 0x0B91;
        public static uint GL_STENCIL_FUNC = 0x0B92;
        public static uint GL_STENCIL_VALUE_MASK = 0x0B93;
        public static uint GL_STENCIL_FAIL = 0x0B94;
        public static uint GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95;
        public static uint GL_STENCIL_PASS_DEPTH_PASS = 0x0B96;
        public static uint GL_STENCIL_REF = 0x0B97;
        public static uint GL_STENCIL_WRITEMASK = 0x0B98;
        public static uint GL_MATRIX_MODE = 0x0BA0;
        public static uint GL_VIEWPORT = 0x0BA2;
        public static uint GL_MODELVIEW_STACK_DEPTH = 0x0BA3;
        public static uint GL_PROJECTION_STACK_DEPTH = 0x0BA4;
        public static uint GL_TEXTURE_STACK_DEPTH = 0x0BA5;
        public static uint GL_MODELVIEW_MATRIX = 0x0BA6;
        public static uint GL_PROJECTION_MATRIX = 0x0BA7;
        public static uint GL_TEXTURE_MATRIX = 0x0BA8;
        public static uint GL_ALPHA_TEST_FUNC = 0x0BC1;
        public static uint GL_ALPHA_TEST_REF = 0x0BC2;
        public static uint GL_BLEND_DST = 0x0BE0;
        public static uint GL_BLEND_SRC = 0x0BE1;
        public static uint GL_LOGIC_OP_MODE = 0x0BF0;
        public static uint GL_SCISSOR_BOX = 0x0C10;
        public static uint GL_COLOR_CLEAR_VALUE = 0x0C22;
        public static uint GL_COLOR_WRITEMASK = 0x0C23;
        public static uint GL_MAX_LIGHTS = 0x0D31;
        public static uint GL_MAX_CLIP_PLANES = 0x0D32;
        public static uint GL_MAX_TEXTURE_SIZE = 0x0D33;
        public static uint GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36;
        public static uint GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38;
        public static uint GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39;
        public static uint GL_MAX_VIEWPORT_DIMS = 0x0D3A;
        public static uint GL_MAX_TEXTURE_UNITS = 0x84E2;
        public static uint GL_SUBPIXEL_BITS = 0x0D50;
        public static uint GL_RED_BITS = 0x0D52;
        public static uint GL_GREEN_BITS = 0x0D53;
        public static uint GL_BLUE_BITS = 0x0D54;
        public static uint GL_ALPHA_BITS = 0x0D55;
        public static uint GL_DEPTH_BITS = 0x0D56;
        public static uint GL_STENCIL_BITS = 0x0D57;
        public static uint GL_POLYGON_OFFSET_UNITS = 0x2A00;
        public static uint GL_POLYGON_OFFSET_FILL = 0x8037;
        public static uint GL_POLYGON_OFFSET_FACTOR = 0x8038;
        public static uint GL_TEXTURE_BINDING_2D = 0x8069;
        public static uint GL_VERTEX_ARRAY_SIZE = 0x807A;
        public static uint GL_VERTEX_ARRAY_TYPE = 0x807B;
        public static uint GL_VERTEX_ARRAY_STRIDE = 0x807C;
        public static uint GL_NORMAL_ARRAY_TYPE = 0x807E;
        public static uint GL_NORMAL_ARRAY_STRIDE = 0x807F;
        public static uint GL_COLOR_ARRAY_SIZE = 0x8081;
        public static uint GL_COLOR_ARRAY_TYPE = 0x8082;
        public static uint GL_COLOR_ARRAY_STRIDE = 0x8083;
        public static uint GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088;
        public static uint GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089;
        public static uint GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A;
        public static uint GL_VERTEX_ARRAY_POINTER = 0x808E;
        public static uint GL_NORMAL_ARRAY_POINTER = 0x808F;
        public static uint GL_COLOR_ARRAY_POINTER = 0x8090;
        public static uint GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092;
        public static uint GL_SAMPLE_BUFFERS = 0x80A8;
        public static uint GL_SAMPLES = 0x80A9;
        public static uint GL_SAMPLE_COVERAGE_VALUE = 0x80AA;
        public static uint GL_SAMPLE_COVERAGE_INVERT = 0x80AB;
        public static uint GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2;
        public static uint GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3;
        public static uint GL_DONT_CARE = 0x1100;
        public static uint GL_FASTEST = 0x1101;
        public static uint GL_NICEST = 0x1102;
        public static uint GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50;
        public static uint GL_POINT_SMOOTH_HINT = 0x0C51;
        public static uint GL_LINE_SMOOTH_HINT = 0x0C52;
        public static uint GL_FOG_HINT = 0x0C54;
        public static uint GL_GENERATE_MIPMAP_HINT = 0x8192;
        public static uint GL_LIGHT_MODEL_AMBIENT = 0x0B53;
        public static uint GL_LIGHT_MODEL_TWO_SIDE = 0x0B52;
        public static uint GL_AMBIENT = 0x1200;
        public static uint GL_DIFFUSE = 0x1201;
        public static uint GL_SPECULAR = 0x1202;
        public static uint GL_POSITION = 0x1203;
        public static uint GL_SPOT_DIRECTION = 0x1204;
        public static uint GL_SPOT_EXPONENT = 0x1205;
        public static uint GL_SPOT_CUTOFF = 0x1206;
        public static uint GL_CONSTANT_ATTENUATION = 0x1207;
        public static uint GL_LINEAR_ATTENUATION = 0x1208;
        public static uint GL_QUADRATIC_ATTENUATION = 0x1209;
        public static uint GL_BYTE = 0x1400;
        public static uint GL_UNSIGNED_BYTE = 0x1401;
        public static uint GL_SHORT = 0x1402;
        public static uint GL_UNSIGNED_SHORT = 0x1403;
        public static uint GL_FLOAT = 0x1406;
        public static uint GL_FIXED = 0x140C;
        public static uint GL_CLEAR = 0x1500;
        public static uint GL_AND = 0x1501;
        public static uint GL_AND_REVERSE = 0x1502;
        public static uint GL_COPY = 0x1503;
        public static uint GL_AND_INVERTED = 0x1504;
        public static uint GL_NOOP = 0x1505;
        public static uint GL_XOR = 0x1506;
        public static uint GL_OR = 0x1507;
        public static uint GL_NOR = 0x1508;
        public static uint GL_EQUIV = 0x1509;
        public static uint GL_INVERT = 0x150A;
        public static uint GL_OR_REVERSE = 0x150B;
        public static uint GL_COPY_INVERTED = 0x150C;
        public static uint GL_OR_INVERTED = 0x150D;
        public static uint GL_NAND = 0x150E;
        public static uint GL_SET = 0x150F;
        public static uint GL_EMISSION = 0x1600;
        public static uint GL_SHININESS = 0x1601;
        public static uint GL_AMBIENT_AND_DIFFUSE = 0x1602;
        public static uint GL_MODELVIEW = 0x1700;
        public static uint GL_PROJECTION = 0x1701;
        public static uint GL_TEXTURE = 0x1702;
        public static uint GL_ALPHA = 0x1906;
        public static uint GL_RGB = 0x1907;
        public static uint GL_RGBA = 0x1908;
        public static uint GL_LUMINANCE = 0x1909;
        public static uint GL_LUMINANCE_ALPHA = 0x190A;
        public static uint GL_UNPACK_ALIGNMENT = 0x0CF5;
        public static uint GL_PACK_ALIGNMENT = 0x0D05;
        public static uint GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033;
        public static uint GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034;
        public static uint GL_UNSIGNED_SHORT_5_6_5 = 0x8363;
        public static uint GL_FLAT = 0x1D00;
        public static uint GL_SMOOTH = 0x1D01;
        public static uint GL_KEEP = 0x1E00;
        public static uint GL_REPLACE = 0x1E01;
        public static uint GL_INCR = 0x1E02;
        public static uint GL_DECR = 0x1E03;
        public static uint GL_VENDOR = 0x1F00;
        public static uint GL_RENDERER = 0x1F01;
        public static uint GL_VERSION = 0x1F02;
        public static uint GL_EXTENSIONS = 0x1F03;
        public static uint GL_MODULATE = 0x2100;
        public static uint GL_DECAL = 0x2101;
        public static uint GL_ADD = 0x0104;
        public static uint GL_TEXTURE_ENV_MODE = 0x2200;
        public static uint GL_TEXTURE_ENV_COLOR = 0x2201;
        public static uint GL_TEXTURE_ENV = 0x2300;
        public static uint GL_NEAREST = 0x2600;
        public static uint GL_LINEAR = 0x2601;
        public static uint GL_NEAREST_MIPMAP_NEAREST = 0x2700;
        public static uint GL_LINEAR_MIPMAP_NEAREST = 0x2701;
        public static uint GL_NEAREST_MIPMAP_LINEAR = 0x2702;
        public static uint GL_LINEAR_MIPMAP_LINEAR = 0x2703;
        public static uint GL_TEXTURE_MAG_FILTER = 0x2800;
        public static uint GL_TEXTURE_MIN_FILTER = 0x2801;
        public static uint GL_TEXTURE_WRAP_S = 0x2802;
        public static uint GL_TEXTURE_WRAP_T = 0x2803;
        public static uint GL_GENERATE_MIPMAP = 0x8191;
        public static uint GL_TEXTURE0 = 0x84C0;
        public static uint GL_TEXTURE1 = 0x84C1;
        public static uint GL_TEXTURE2 = 0x84C2;
        public static uint GL_TEXTURE3 = 0x84C3;
        public static uint GL_TEXTURE4 = 0x84C4;
        public static uint GL_TEXTURE5 = 0x84C5;
        public static uint GL_TEXTURE6 = 0x84C6;
        public static uint GL_TEXTURE7 = 0x84C7;
        public static uint GL_TEXTURE8 = 0x84C8;
        public static uint GL_TEXTURE9 = 0x84C9;
        public static uint GL_TEXTURE10 = 0x84CA;
        public static uint GL_TEXTURE11 = 0x84CB;
        public static uint GL_TEXTURE12 = 0x84CC;
        public static uint GL_TEXTURE13 = 0x84CD;
        public static uint GL_TEXTURE14 = 0x84CE;
        public static uint GL_TEXTURE15 = 0x84CF;
        public static uint GL_TEXTURE16 = 0x84D0;
        public static uint GL_TEXTURE17 = 0x84D1;
        public static uint GL_TEXTURE18 = 0x84D2;
        public static uint GL_TEXTURE19 = 0x84D3;
        public static uint GL_TEXTURE20 = 0x84D4;
        public static uint GL_TEXTURE21 = 0x84D5;
        public static uint GL_TEXTURE22 = 0x84D6;
        public static uint GL_TEXTURE23 = 0x84D7;
        public static uint GL_TEXTURE24 = 0x84D8;
        public static uint GL_TEXTURE25 = 0x84D9;
        public static uint GL_TEXTURE26 = 0x84DA;
        public static uint GL_TEXTURE27 = 0x84DB;
        public static uint GL_TEXTURE28 = 0x84DC;
        public static uint GL_TEXTURE29 = 0x84DD;
        public static uint GL_TEXTURE30 = 0x84DE;
        public static uint GL_TEXTURE31 = 0x84DF;
        public static uint GL_ACTIVE_TEXTURE = 0x84E0;
        public static uint GL_CLIENT_ACTIVE_TEXTURE = 0x84E1;
        public static uint GL_REPEAT = 0x2901;
        public static uint GL_CLAMP_TO_EDGE = 0x812F;
        public static uint GL_LIGHT0 = 0x4000;
        public static uint GL_LIGHT1 = 0x4001;
        public static uint GL_LIGHT2 = 0x4002;
        public static uint GL_LIGHT3 = 0x4003;
        public static uint GL_LIGHT4 = 0x4004;
        public static uint GL_LIGHT5 = 0x4005;
        public static uint GL_LIGHT6 = 0x4006;
        public static uint GL_LIGHT7 = 0x4007;
        public static uint GL_ARRAY_BUFFER = 0x8892;
        public static uint GL_ELEMENT_ARRAY_BUFFER = 0x8893;
        public static uint GL_ARRAY_BUFFER_BINDING = 0x8894;
        public static uint GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895;
        public static uint GL_VERTEX_ARRAY_BUFFER_BINDING = 0x8896;
        public static uint GL_NORMAL_ARRAY_BUFFER_BINDING = 0x8897;
        public static uint GL_COLOR_ARRAY_BUFFER_BINDING = 0x8898;
        public static uint GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A;
        public static uint GL_STATIC_DRAW = 0x88E4;
        public static uint GL_DYNAMIC_DRAW = 0x88E8;
        public static uint GL_BUFFER_SIZE = 0x8764;
        public static uint GL_BUFFER_USAGE = 0x8765;
        public static uint GL_SUBTRACT = 0x84E7;
        public static uint GL_COMBINE = 0x8570;
        public static uint GL_COMBINE_RGB = 0x8571;
        public static uint GL_COMBINE_ALPHA = 0x8572;
        public static uint GL_RGB_SCALE = 0x8573;
        public static uint GL_ADD_SIGNED = 0x8574;
        public static uint GL_INTERPOLATE = 0x8575;
        public static uint GL_CONSTANT = 0x8576;
        public static uint GL_PRIMARY_COLOR = 0x8577;
        public static uint GL_PREVIOUS = 0x8578;
        public static uint GL_OPERAND0_RGB = 0x8590;
        public static uint GL_OPERAND1_RGB = 0x8591;
        public static uint GL_OPERAND2_RGB = 0x8592;
        public static uint GL_OPERAND0_ALPHA = 0x8598;
        public static uint GL_OPERAND1_ALPHA = 0x8599;
        public static uint GL_OPERAND2_ALPHA = 0x859A;
        public static uint GL_ALPHA_SCALE = 0x0D1C;
        public static uint GL_SRC0_RGB = 0x8580;
        public static uint GL_SRC1_RGB = 0x8581;
        public static uint GL_SRC2_RGB = 0x8582;
        public static uint GL_SRC0_ALPHA = 0x8588;
        public static uint GL_SRC1_ALPHA = 0x8589;
        public static uint GL_SRC2_ALPHA = 0x858A;
        public static uint GL_DOT3_RGB = 0x86AE;
        public static uint GL_DOT3_RGBA = 0x86AF;
        #endregion

        #region Commands
        public static void glAlphaFunc(uint func, float @ref)
        {
            glAlphaFuncPtr(func, @ref);
        }
        public static void glClearColor(float red, float green, float blue, float alpha)
        {
            glClearColorPtr(red, green, blue, alpha);
        }
        public static void glClearDepthf(float d)
        {
            glClearDepthfPtr(d);
        }
        public static void glClipPlanef(uint p, IntPtr eqn)
        {
            glClipPlanefPtr(p, eqn);
        }
        public static void glColor4f(float red, float green, float blue, float alpha)
        {
            glColor4fPtr(red, green, blue, alpha);
        }
        public static void glDepthRangef(float n, float f)
        {
            glDepthRangefPtr(n, f);
        }
        public static void glFogf(uint pname, float param)
        {
            glFogfPtr(pname, param);
        }
        public static void glFogfv(uint pname, IntPtr @params)
        {
            glFogfvPtr(pname, @params);
        }
        public static void glFrustumf(float l, float r, float b, float t, float n, float f)
        {
            glFrustumfPtr(l, r, b, t, n, f);
        }
        public static void glGetClipPlanef(uint plane, IntPtr equation)
        {
            glGetClipPlanefPtr(plane, equation);
        }
        public static void glGetFloatv(uint pname, IntPtr data)
        {
            glGetFloatvPtr(pname, data);
        }
        public static void glGetLightfv(uint light, uint pname, IntPtr @params)
        {
            glGetLightfvPtr(light, pname, @params);
        }
        public static void glGetMaterialfv(uint face, uint pname, IntPtr @params)
        {
            glGetMaterialfvPtr(face, pname, @params);
        }
        public static void glGetTexEnvfv(uint target, uint pname, IntPtr @params)
        {
            glGetTexEnvfvPtr(target, pname, @params);
        }
        public static void glGetTexParameterfv(uint target, uint pname, IntPtr @params)
        {
            glGetTexParameterfvPtr(target, pname, @params);
        }
        public static void glLightModelf(uint pname, float param)
        {
            glLightModelfPtr(pname, param);
        }
        public static void glLightModelfv(uint pname, IntPtr @params)
        {
            glLightModelfvPtr(pname, @params);
        }
        public static void glLightf(uint light, uint pname, float param)
        {
            glLightfPtr(light, pname, param);
        }
        public static void glLightfv(uint light, uint pname, IntPtr @params)
        {
            glLightfvPtr(light, pname, @params);
        }
        public static void glLineWidth(float width)
        {
            glLineWidthPtr(width);
        }
        public static void glLoadMatrixf(IntPtr m)
        {
            glLoadMatrixfPtr(m);
        }
        public static void glMaterialf(uint face, uint pname, float param)
        {
            glMaterialfPtr(face, pname, param);
        }
        public static void glMaterialfv(uint face, uint pname, IntPtr @params)
        {
            glMaterialfvPtr(face, pname, @params);
        }
        public static void glMultMatrixf(IntPtr m)
        {
            glMultMatrixfPtr(m);
        }
        public static void glMultiTexCoord4f(uint target, float s, float t, float r, float q)
        {
            glMultiTexCoord4fPtr(target, s, t, r, q);
        }
        public static void glNormal3f(float nx, float ny, float nz)
        {
            glNormal3fPtr(nx, ny, nz);
        }
        public static void glOrthof(float l, float r, float b, float t, float n, float f)
        {
            glOrthofPtr(l, r, b, t, n, f);
        }
        public static void glPointParameterf(uint pname, float param)
        {
            glPointParameterfPtr(pname, param);
        }
        public static void glPointParameterfv(uint pname, IntPtr @params)
        {
            glPointParameterfvPtr(pname, @params);
        }
        public static void glPointSize(float size)
        {
            glPointSizePtr(size);
        }
        public static void glPolygonOffset(float factor, float units)
        {
            glPolygonOffsetPtr(factor, units);
        }
        public static void glRotatef(float angle, float x, float y, float z)
        {
            glRotatefPtr(angle, x, y, z);
        }
        public static void glScalef(float x, float y, float z)
        {
            glScalefPtr(x, y, z);
        }
        public static void glTexEnvf(uint target, uint pname, float param)
        {
            glTexEnvfPtr(target, pname, param);
        }
        public static void glTexEnvfv(uint target, uint pname, IntPtr @params)
        {
            glTexEnvfvPtr(target, pname, @params);
        }
        public static void glTexParameterf(uint target, uint pname, float param)
        {
            glTexParameterfPtr(target, pname, param);
        }
        public static void glTexParameterfv(uint target, uint pname, IntPtr @params)
        {
            glTexParameterfvPtr(target, pname, @params);
        }
        public static void glTranslatef(float x, float y, float z)
        {
            glTranslatefPtr(x, y, z);
        }
        public static void glActiveTexture(uint texture)
        {
            glActiveTexturePtr(texture);
        }
        public static void glAlphaFuncx(uint func, int @ref)
        {
            glAlphaFuncxPtr(func, @ref);
        }
        public static void glBindBuffer(uint target, uint buffer)
        {
            glBindBufferPtr(target, buffer);
        }
        public static void glBindTexture(uint target, uint texture)
        {
            glBindTexturePtr(target, texture);
        }
        public static void glBlendFunc(uint sfactor, uint dfactor)
        {
            glBlendFuncPtr(sfactor, dfactor);
        }
        public static void glBufferData(uint target, int size, IntPtr data, uint usage)
        {
            glBufferDataPtr(target, size, data, usage);
        }
        public static void glBufferSubData(uint target, IntPtr offset, int size, IntPtr data)
        {
            glBufferSubDataPtr(target, offset, size, data);
        }
        public static void glClear(uint mask)
        {
            glClearPtr(mask);
        }
        public static void glClearColorx(int red, int green, int blue, int alpha)
        {
            glClearColorxPtr(red, green, blue, alpha);
        }
        public static void glClearDepthx(int depth)
        {
            glClearDepthxPtr(depth);
        }
        public static void glClearStencil(int s)
        {
            glClearStencilPtr(s);
        }
        public static void glClientActiveTexture(uint texture)
        {
            glClientActiveTexturePtr(texture);
        }
        public static void glClipPlanex(uint plane, IntPtr equation)
        {
            glClipPlanexPtr(plane, equation);
        }
        public static void glColor4ub(byte red, byte green, byte blue, byte alpha)
        {
            glColor4ubPtr(red, green, blue, alpha);
        }
        public static void glColor4x(int red, int green, int blue, int alpha)
        {
            glColor4xPtr(red, green, blue, alpha);
        }
        public static void glColorMask(bool red, bool green, bool blue, bool alpha)
        {
            glColorMaskPtr(red, green, blue, alpha);
        }
        public static void glColorPointer(int size, uint type, int stride, IntPtr pointer)
        {
            glColorPointerPtr(size, type, stride, pointer);
        }
        public static void glCompressedTexImage2D(uint target, int level, uint internalformat, int width, int height, int border, int imageSize, IntPtr data)
        {
            glCompressedTexImage2DPtr(target, level, internalformat, width, height, border, imageSize, data);
        }
        public static void glCompressedTexSubImage2D(uint target, int level, int xoffset, int yoffset, int width, int height, uint format, int imageSize, IntPtr data)
        {
            glCompressedTexSubImage2DPtr(target, level, xoffset, yoffset, width, height, format, imageSize, data);
        }
        public static void glCopyTexImage2D(uint target, int level, uint internalformat, int x, int y, int width, int height, int border)
        {
            glCopyTexImage2DPtr(target, level, internalformat, x, y, width, height, border);
        }
        public static void glCopyTexSubImage2D(uint target, int level, int xoffset, int yoffset, int x, int y, int width, int height)
        {
            glCopyTexSubImage2DPtr(target, level, xoffset, yoffset, x, y, width, height);
        }
        public static void glCullFace(uint mode)
        {
            glCullFacePtr(mode);
        }
        public static void glDeleteBuffers(int n, IntPtr buffers)
        {
            glDeleteBuffersPtr(n, buffers);
        }
        public static void glDeleteTextures(int n, IntPtr textures)
        {
            glDeleteTexturesPtr(n, textures);
        }
        public static void glDepthFunc(uint func)
        {
            glDepthFuncPtr(func);
        }
        public static void glDepthMask(bool flag)
        {
            glDepthMaskPtr(flag);
        }
        public static void glDepthRangex(int n, int f)
        {
            glDepthRangexPtr(n, f);
        }
        public static void glDisable(uint cap)
        {
            glDisablePtr(cap);
        }
        public static void glDisableClientState(uint array)
        {
            glDisableClientStatePtr(array);
        }
        public static void glDrawArrays(uint mode, int first, int count)
        {
            glDrawArraysPtr(mode, first, count);
        }
        public static void glDrawElements(uint mode, int count, uint type, IntPtr indices)
        {
            glDrawElementsPtr(mode, count, type, indices);
        }
        public static void glEnable(uint cap)
        {
            glEnablePtr(cap);
        }
        public static void glEnableClientState(uint array)
        {
            glEnableClientStatePtr(array);
        }
        public static void glFinish()
        {
            glFinishPtr();
        }
        public static void glFlush()
        {
            glFlushPtr();
        }
        public static void glFogx(uint pname, int param)
        {
            glFogxPtr(pname, param);
        }
        public static void glFogxv(uint pname, IntPtr param)
        {
            glFogxvPtr(pname, param);
        }
        public static void glFrontFace(uint mode)
        {
            glFrontFacePtr(mode);
        }
        public static void glFrustumx(int l, int r, int b, int t, int n, int f)
        {
            glFrustumxPtr(l, r, b, t, n, f);
        }
        public static void glGetBooleanv(uint pname, IntPtr data)
        {
            glGetBooleanvPtr(pname, data);
        }
        public static void glGetBufferParameteriv(uint target, uint pname, IntPtr @params)
        {
            glGetBufferParameterivPtr(target, pname, @params);
        }
        public static void glGetClipPlanex(uint plane, IntPtr equation)
        {
            glGetClipPlanexPtr(plane, equation);
        }
        public static void glGenBuffers(int n, IntPtr buffers)
        {
            glGenBuffersPtr(n, buffers);
        }
        public static void glGenTextures(int n, IntPtr textures)
        {
            glGenTexturesPtr(n, textures);
        }
        public static uint glGetError()
        {
            return glGetErrorPtr();
        }
        public static void glGetFixedv(uint pname, IntPtr @params)
        {
            glGetFixedvPtr(pname, @params);
        }
        public static void glGetIntegerv(uint pname, IntPtr data)
        {
            glGetIntegervPtr(pname, data);
        }
        public static void glGetLightxv(uint light, uint pname, IntPtr @params)
        {
            glGetLightxvPtr(light, pname, @params);
        }
        public static void glGetMaterialxv(uint face, uint pname, IntPtr @params)
        {
            glGetMaterialxvPtr(face, pname, @params);
        }
        public static void glGetPointerv(uint pname, IntPtr @params)
        {
            glGetPointervPtr(pname, @params);
        }
        public static IntPtr glGetString(uint name)
        {
            return glGetStringPtr(name);
        }
        public static void glGetTexEnviv(uint target, uint pname, IntPtr @params)
        {
            glGetTexEnvivPtr(target, pname, @params);
        }
        public static void glGetTexEnvxv(uint target, uint pname, IntPtr @params)
        {
            glGetTexEnvxvPtr(target, pname, @params);
        }
        public static void glGetTexParameteriv(uint target, uint pname, IntPtr @params)
        {
            glGetTexParameterivPtr(target, pname, @params);
        }
        public static void glGetTexParameterxv(uint target, uint pname, IntPtr @params)
        {
            glGetTexParameterxvPtr(target, pname, @params);
        }
        public static void glHint(uint target, uint mode)
        {
            glHintPtr(target, mode);
        }
        public static bool glIsBuffer(uint buffer)
        {
            return glIsBufferPtr(buffer);
        }
        public static bool glIsEnabled(uint cap)
        {
            return glIsEnabledPtr(cap);
        }
        public static bool glIsTexture(uint texture)
        {
            return glIsTexturePtr(texture);
        }
        public static void glLightModelx(uint pname, int param)
        {
            glLightModelxPtr(pname, param);
        }
        public static void glLightModelxv(uint pname, IntPtr param)
        {
            glLightModelxvPtr(pname, param);
        }
        public static void glLightx(uint light, uint pname, int param)
        {
            glLightxPtr(light, pname, param);
        }
        public static void glLightxv(uint light, uint pname, IntPtr @params)
        {
            glLightxvPtr(light, pname, @params);
        }
        public static void glLineWidthx(int width)
        {
            glLineWidthxPtr(width);
        }
        public static void glLoadIdentity()
        {
            glLoadIdentityPtr();
        }
        public static void glLoadMatrixx(IntPtr m)
        {
            glLoadMatrixxPtr(m);
        }
        public static void glLogicOp(uint opcode)
        {
            glLogicOpPtr(opcode);
        }
        public static void glMaterialx(uint face, uint pname, int param)
        {
            glMaterialxPtr(face, pname, param);
        }
        public static void glMaterialxv(uint face, uint pname, IntPtr param)
        {
            glMaterialxvPtr(face, pname, param);
        }
        public static void glMatrixMode(uint mode)
        {
            glMatrixModePtr(mode);
        }
        public static void glMultMatrixx(IntPtr m)
        {
            glMultMatrixxPtr(m);
        }
        public static void glMultiTexCoord4x(uint texture, int s, int t, int r, int q)
        {
            glMultiTexCoord4xPtr(texture, s, t, r, q);
        }
        public static void glNormal3x(int nx, int ny, int nz)
        {
            glNormal3xPtr(nx, ny, nz);
        }
        public static void glNormalPointer(uint type, int stride, IntPtr pointer)
        {
            glNormalPointerPtr(type, stride, pointer);
        }
        public static void glOrthox(int l, int r, int b, int t, int n, int f)
        {
            glOrthoxPtr(l, r, b, t, n, f);
        }
        public static void glPixelStorei(uint pname, int param)
        {
            glPixelStoreiPtr(pname, param);
        }
        public static void glPointParameterx(uint pname, int param)
        {
            glPointParameterxPtr(pname, param);
        }
        public static void glPointParameterxv(uint pname, IntPtr @params)
        {
            glPointParameterxvPtr(pname, @params);
        }
        public static void glPointSizex(int size)
        {
            glPointSizexPtr(size);
        }
        public static void glPolygonOffsetx(int factor, int units)
        {
            glPolygonOffsetxPtr(factor, units);
        }
        public static void glPopMatrix()
        {
            glPopMatrixPtr();
        }
        public static void glPushMatrix()
        {
            glPushMatrixPtr();
        }
        public static void glReadPixels(int x, int y, int width, int height, uint format, uint type, IntPtr pixels)
        {
            glReadPixelsPtr(x, y, width, height, format, type, pixels);
        }
        public static void glRotatex(int angle, int x, int y, int z)
        {
            glRotatexPtr(angle, x, y, z);
        }
        public static void glSampleCoverage(float value, bool invert)
        {
            glSampleCoveragePtr(value, invert);
        }
        public static void glSampleCoveragex(int value, bool invert)
        {
            glSampleCoveragexPtr(value, invert);
        }
        public static void glScalex(int x, int y, int z)
        {
            glScalexPtr(x, y, z);
        }
        public static void glScissor(int x, int y, int width, int height)
        {
            glScissorPtr(x, y, width, height);
        }
        public static void glShadeModel(uint mode)
        {
            glShadeModelPtr(mode);
        }
        public static void glStencilFunc(uint func, int @ref, uint mask)
        {
            glStencilFuncPtr(func, @ref, mask);
        }
        public static void glStencilMask(uint mask)
        {
            glStencilMaskPtr(mask);
        }
        public static void glStencilOp(uint fail, uint zfail, uint zpass)
        {
            glStencilOpPtr(fail, zfail, zpass);
        }
        public static void glTexCoordPointer(int size, uint type, int stride, IntPtr pointer)
        {
            glTexCoordPointerPtr(size, type, stride, pointer);
        }
        public static void glTexEnvi(uint target, uint pname, int param)
        {
            glTexEnviPtr(target, pname, param);
        }
        public static void glTexEnvx(uint target, uint pname, int param)
        {
            glTexEnvxPtr(target, pname, param);
        }
        public static void glTexEnviv(uint target, uint pname, IntPtr @params)
        {
            glTexEnvivPtr(target, pname, @params);
        }
        public static void glTexEnvxv(uint target, uint pname, IntPtr @params)
        {
            glTexEnvxvPtr(target, pname, @params);
        }
        public static void glTexImage2D(uint target, int level, int internalformat, int width, int height, int border, uint format, uint type, IntPtr pixels)
        {
            glTexImage2DPtr(target, level, internalformat, width, height, border, format, type, pixels);
        }
        public static void glTexParameteri(uint target, uint pname, int param)
        {
            glTexParameteriPtr(target, pname, param);
        }
        public static void glTexParameterx(uint target, uint pname, int param)
        {
            glTexParameterxPtr(target, pname, param);
        }
        public static void glTexParameteriv(uint target, uint pname, IntPtr @params)
        {
            glTexParameterivPtr(target, pname, @params);
        }
        public static void glTexParameterxv(uint target, uint pname, IntPtr @params)
        {
            glTexParameterxvPtr(target, pname, @params);
        }
        public static void glTexSubImage2D(uint target, int level, int xoffset, int yoffset, int width, int height, uint format, uint type, IntPtr pixels)
        {
            glTexSubImage2DPtr(target, level, xoffset, yoffset, width, height, format, type, pixels);
        }
        public static void glTranslatex(int x, int y, int z)
        {
            glTranslatexPtr(x, y, z);
        }
        public static void glVertexPointer(int size, uint type, int stride, IntPtr pointer)
        {
            glVertexPointerPtr(size, type, stride, pointer);
        }
        public static void glViewport(int x, int y, int width, int height)
        {
            glViewportPtr(x, y, width, height);
        }
        #endregion

        #region Command Delegates
        private delegate void glAlphaFuncFunc(uint func, float @ref);
        private static glAlphaFuncFunc glAlphaFuncPtr;
        private delegate void glClearColorFunc(float red, float green, float blue, float alpha);
        private static glClearColorFunc glClearColorPtr;
        private delegate void glClearDepthfFunc(float d);
        private static glClearDepthfFunc glClearDepthfPtr;
        private delegate void glClipPlanefFunc(uint p, IntPtr eqn);
        private static glClipPlanefFunc glClipPlanefPtr;
        private delegate void glColor4fFunc(float red, float green, float blue, float alpha);
        private static glColor4fFunc glColor4fPtr;
        private delegate void glDepthRangefFunc(float n, float f);
        private static glDepthRangefFunc glDepthRangefPtr;
        private delegate void glFogfFunc(uint pname, float param);
        private static glFogfFunc glFogfPtr;
        private delegate void glFogfvFunc(uint pname, IntPtr @params);
        private static glFogfvFunc glFogfvPtr;
        private delegate void glFrustumfFunc(float l, float r, float b, float t, float n, float f);
        private static glFrustumfFunc glFrustumfPtr;
        private delegate void glGetClipPlanefFunc(uint plane, IntPtr equation);
        private static glGetClipPlanefFunc glGetClipPlanefPtr;
        private delegate void glGetFloatvFunc(uint pname, IntPtr data);
        private static glGetFloatvFunc glGetFloatvPtr;
        private delegate void glGetLightfvFunc(uint light, uint pname, IntPtr @params);
        private static glGetLightfvFunc glGetLightfvPtr;
        private delegate void glGetMaterialfvFunc(uint face, uint pname, IntPtr @params);
        private static glGetMaterialfvFunc glGetMaterialfvPtr;
        private delegate void glGetTexEnvfvFunc(uint target, uint pname, IntPtr @params);
        private static glGetTexEnvfvFunc glGetTexEnvfvPtr;
        private delegate void glGetTexParameterfvFunc(uint target, uint pname, IntPtr @params);
        private static glGetTexParameterfvFunc glGetTexParameterfvPtr;
        private delegate void glLightModelfFunc(uint pname, float param);
        private static glLightModelfFunc glLightModelfPtr;
        private delegate void glLightModelfvFunc(uint pname, IntPtr @params);
        private static glLightModelfvFunc glLightModelfvPtr;
        private delegate void glLightfFunc(uint light, uint pname, float param);
        private static glLightfFunc glLightfPtr;
        private delegate void glLightfvFunc(uint light, uint pname, IntPtr @params);
        private static glLightfvFunc glLightfvPtr;
        private delegate void glLineWidthFunc(float width);
        private static glLineWidthFunc glLineWidthPtr;
        private delegate void glLoadMatrixfFunc(IntPtr m);
        private static glLoadMatrixfFunc glLoadMatrixfPtr;
        private delegate void glMaterialfFunc(uint face, uint pname, float param);
        private static glMaterialfFunc glMaterialfPtr;
        private delegate void glMaterialfvFunc(uint face, uint pname, IntPtr @params);
        private static glMaterialfvFunc glMaterialfvPtr;
        private delegate void glMultMatrixfFunc(IntPtr m);
        private static glMultMatrixfFunc glMultMatrixfPtr;
        private delegate void glMultiTexCoord4fFunc(uint target, float s, float t, float r, float q);
        private static glMultiTexCoord4fFunc glMultiTexCoord4fPtr;
        private delegate void glNormal3fFunc(float nx, float ny, float nz);
        private static glNormal3fFunc glNormal3fPtr;
        private delegate void glOrthofFunc(float l, float r, float b, float t, float n, float f);
        private static glOrthofFunc glOrthofPtr;
        private delegate void glPointParameterfFunc(uint pname, float param);
        private static glPointParameterfFunc glPointParameterfPtr;
        private delegate void glPointParameterfvFunc(uint pname, IntPtr @params);
        private static glPointParameterfvFunc glPointParameterfvPtr;
        private delegate void glPointSizeFunc(float size);
        private static glPointSizeFunc glPointSizePtr;
        private delegate void glPolygonOffsetFunc(float factor, float units);
        private static glPolygonOffsetFunc glPolygonOffsetPtr;
        private delegate void glRotatefFunc(float angle, float x, float y, float z);
        private static glRotatefFunc glRotatefPtr;
        private delegate void glScalefFunc(float x, float y, float z);
        private static glScalefFunc glScalefPtr;
        private delegate void glTexEnvfFunc(uint target, uint pname, float param);
        private static glTexEnvfFunc glTexEnvfPtr;
        private delegate void glTexEnvfvFunc(uint target, uint pname, IntPtr @params);
        private static glTexEnvfvFunc glTexEnvfvPtr;
        private delegate void glTexParameterfFunc(uint target, uint pname, float param);
        private static glTexParameterfFunc glTexParameterfPtr;
        private delegate void glTexParameterfvFunc(uint target, uint pname, IntPtr @params);
        private static glTexParameterfvFunc glTexParameterfvPtr;
        private delegate void glTranslatefFunc(float x, float y, float z);
        private static glTranslatefFunc glTranslatefPtr;
        private delegate void glActiveTextureFunc(uint texture);
        private static glActiveTextureFunc glActiveTexturePtr;
        private delegate void glAlphaFuncxFunc(uint func, int @ref);
        private static glAlphaFuncxFunc glAlphaFuncxPtr;
        private delegate void glBindBufferFunc(uint target, uint buffer);
        private static glBindBufferFunc glBindBufferPtr;
        private delegate void glBindTextureFunc(uint target, uint texture);
        private static glBindTextureFunc glBindTexturePtr;
        private delegate void glBlendFuncFunc(uint sfactor, uint dfactor);
        private static glBlendFuncFunc glBlendFuncPtr;
        private delegate void glBufferDataFunc(uint target, int size, IntPtr data, uint usage);
        private static glBufferDataFunc glBufferDataPtr;
        private delegate void glBufferSubDataFunc(uint target, IntPtr offset, int size, IntPtr data);
        private static glBufferSubDataFunc glBufferSubDataPtr;
        private delegate void glClearFunc(uint mask);
        private static glClearFunc glClearPtr;
        private delegate void glClearColorxFunc(int red, int green, int blue, int alpha);
        private static glClearColorxFunc glClearColorxPtr;
        private delegate void glClearDepthxFunc(int depth);
        private static glClearDepthxFunc glClearDepthxPtr;
        private delegate void glClearStencilFunc(int s);
        private static glClearStencilFunc glClearStencilPtr;
        private delegate void glClientActiveTextureFunc(uint texture);
        private static glClientActiveTextureFunc glClientActiveTexturePtr;
        private delegate void glClipPlanexFunc(uint plane, IntPtr equation);
        private static glClipPlanexFunc glClipPlanexPtr;
        private delegate void glColor4ubFunc(byte red, byte green, byte blue, byte alpha);
        private static glColor4ubFunc glColor4ubPtr;
        private delegate void glColor4xFunc(int red, int green, int blue, int alpha);
        private static glColor4xFunc glColor4xPtr;
        private delegate void glColorMaskFunc(bool red, bool green, bool blue, bool alpha);
        private static glColorMaskFunc glColorMaskPtr;
        private delegate void glColorPointerFunc(int size, uint type, int stride, IntPtr pointer);
        private static glColorPointerFunc glColorPointerPtr;
        private delegate void glCompressedTexImage2DFunc(uint target, int level, uint internalformat, int width, int height, int border, int imageSize, IntPtr data);
        private static glCompressedTexImage2DFunc glCompressedTexImage2DPtr;
        private delegate void glCompressedTexSubImage2DFunc(uint target, int level, int xoffset, int yoffset, int width, int height, uint format, int imageSize, IntPtr data);
        private static glCompressedTexSubImage2DFunc glCompressedTexSubImage2DPtr;
        private delegate void glCopyTexImage2DFunc(uint target, int level, uint internalformat, int x, int y, int width, int height, int border);
        private static glCopyTexImage2DFunc glCopyTexImage2DPtr;
        private delegate void glCopyTexSubImage2DFunc(uint target, int level, int xoffset, int yoffset, int x, int y, int width, int height);
        private static glCopyTexSubImage2DFunc glCopyTexSubImage2DPtr;
        private delegate void glCullFaceFunc(uint mode);
        private static glCullFaceFunc glCullFacePtr;
        private delegate void glDeleteBuffersFunc(int n, IntPtr buffers);
        private static glDeleteBuffersFunc glDeleteBuffersPtr;
        private delegate void glDeleteTexturesFunc(int n, IntPtr textures);
        private static glDeleteTexturesFunc glDeleteTexturesPtr;
        private delegate void glDepthFuncFunc(uint func);
        private static glDepthFuncFunc glDepthFuncPtr;
        private delegate void glDepthMaskFunc(bool flag);
        private static glDepthMaskFunc glDepthMaskPtr;
        private delegate void glDepthRangexFunc(int n, int f);
        private static glDepthRangexFunc glDepthRangexPtr;
        private delegate void glDisableFunc(uint cap);
        private static glDisableFunc glDisablePtr;
        private delegate void glDisableClientStateFunc(uint array);
        private static glDisableClientStateFunc glDisableClientStatePtr;
        private delegate void glDrawArraysFunc(uint mode, int first, int count);
        private static glDrawArraysFunc glDrawArraysPtr;
        private delegate void glDrawElementsFunc(uint mode, int count, uint type, IntPtr indices);
        private static glDrawElementsFunc glDrawElementsPtr;
        private delegate void glEnableFunc(uint cap);
        private static glEnableFunc glEnablePtr;
        private delegate void glEnableClientStateFunc(uint array);
        private static glEnableClientStateFunc glEnableClientStatePtr;
        private delegate void glFinishFunc();
        private static glFinishFunc glFinishPtr;
        private delegate void glFlushFunc();
        private static glFlushFunc glFlushPtr;
        private delegate void glFogxFunc(uint pname, int param);
        private static glFogxFunc glFogxPtr;
        private delegate void glFogxvFunc(uint pname, IntPtr param);
        private static glFogxvFunc glFogxvPtr;
        private delegate void glFrontFaceFunc(uint mode);
        private static glFrontFaceFunc glFrontFacePtr;
        private delegate void glFrustumxFunc(int l, int r, int b, int t, int n, int f);
        private static glFrustumxFunc glFrustumxPtr;
        private delegate void glGetBooleanvFunc(uint pname, IntPtr data);
        private static glGetBooleanvFunc glGetBooleanvPtr;
        private delegate void glGetBufferParameterivFunc(uint target, uint pname, IntPtr @params);
        private static glGetBufferParameterivFunc glGetBufferParameterivPtr;
        private delegate void glGetClipPlanexFunc(uint plane, IntPtr equation);
        private static glGetClipPlanexFunc glGetClipPlanexPtr;
        private delegate void glGenBuffersFunc(int n, IntPtr buffers);
        private static glGenBuffersFunc glGenBuffersPtr;
        private delegate void glGenTexturesFunc(int n, IntPtr textures);
        private static glGenTexturesFunc glGenTexturesPtr;
        private delegate uint glGetErrorFunc();
        private static glGetErrorFunc glGetErrorPtr;
        private delegate void glGetFixedvFunc(uint pname, IntPtr @params);
        private static glGetFixedvFunc glGetFixedvPtr;
        private delegate void glGetIntegervFunc(uint pname, IntPtr data);
        private static glGetIntegervFunc glGetIntegervPtr;
        private delegate void glGetLightxvFunc(uint light, uint pname, IntPtr @params);
        private static glGetLightxvFunc glGetLightxvPtr;
        private delegate void glGetMaterialxvFunc(uint face, uint pname, IntPtr @params);
        private static glGetMaterialxvFunc glGetMaterialxvPtr;
        private delegate void glGetPointervFunc(uint pname, IntPtr @params);
        private static glGetPointervFunc glGetPointervPtr;
        private delegate IntPtr glGetStringFunc(uint name);
        private static glGetStringFunc glGetStringPtr;
        private delegate void glGetTexEnvivFunc(uint target, uint pname, IntPtr @params);
        private static glGetTexEnvivFunc glGetTexEnvivPtr;
        private delegate void glGetTexEnvxvFunc(uint target, uint pname, IntPtr @params);
        private static glGetTexEnvxvFunc glGetTexEnvxvPtr;
        private delegate void glGetTexParameterivFunc(uint target, uint pname, IntPtr @params);
        private static glGetTexParameterivFunc glGetTexParameterivPtr;
        private delegate void glGetTexParameterxvFunc(uint target, uint pname, IntPtr @params);
        private static glGetTexParameterxvFunc glGetTexParameterxvPtr;
        private delegate void glHintFunc(uint target, uint mode);
        private static glHintFunc glHintPtr;
        private delegate bool glIsBufferFunc(uint buffer);
        private static glIsBufferFunc glIsBufferPtr;
        private delegate bool glIsEnabledFunc(uint cap);
        private static glIsEnabledFunc glIsEnabledPtr;
        private delegate bool glIsTextureFunc(uint texture);
        private static glIsTextureFunc glIsTexturePtr;
        private delegate void glLightModelxFunc(uint pname, int param);
        private static glLightModelxFunc glLightModelxPtr;
        private delegate void glLightModelxvFunc(uint pname, IntPtr param);
        private static glLightModelxvFunc glLightModelxvPtr;
        private delegate void glLightxFunc(uint light, uint pname, int param);
        private static glLightxFunc glLightxPtr;
        private delegate void glLightxvFunc(uint light, uint pname, IntPtr @params);
        private static glLightxvFunc glLightxvPtr;
        private delegate void glLineWidthxFunc(int width);
        private static glLineWidthxFunc glLineWidthxPtr;
        private delegate void glLoadIdentityFunc();
        private static glLoadIdentityFunc glLoadIdentityPtr;
        private delegate void glLoadMatrixxFunc(IntPtr m);
        private static glLoadMatrixxFunc glLoadMatrixxPtr;
        private delegate void glLogicOpFunc(uint opcode);
        private static glLogicOpFunc glLogicOpPtr;
        private delegate void glMaterialxFunc(uint face, uint pname, int param);
        private static glMaterialxFunc glMaterialxPtr;
        private delegate void glMaterialxvFunc(uint face, uint pname, IntPtr param);
        private static glMaterialxvFunc glMaterialxvPtr;
        private delegate void glMatrixModeFunc(uint mode);
        private static glMatrixModeFunc glMatrixModePtr;
        private delegate void glMultMatrixxFunc(IntPtr m);
        private static glMultMatrixxFunc glMultMatrixxPtr;
        private delegate void glMultiTexCoord4xFunc(uint texture, int s, int t, int r, int q);
        private static glMultiTexCoord4xFunc glMultiTexCoord4xPtr;
        private delegate void glNormal3xFunc(int nx, int ny, int nz);
        private static glNormal3xFunc glNormal3xPtr;
        private delegate void glNormalPointerFunc(uint type, int stride, IntPtr pointer);
        private static glNormalPointerFunc glNormalPointerPtr;
        private delegate void glOrthoxFunc(int l, int r, int b, int t, int n, int f);
        private static glOrthoxFunc glOrthoxPtr;
        private delegate void glPixelStoreiFunc(uint pname, int param);
        private static glPixelStoreiFunc glPixelStoreiPtr;
        private delegate void glPointParameterxFunc(uint pname, int param);
        private static glPointParameterxFunc glPointParameterxPtr;
        private delegate void glPointParameterxvFunc(uint pname, IntPtr @params);
        private static glPointParameterxvFunc glPointParameterxvPtr;
        private delegate void glPointSizexFunc(int size);
        private static glPointSizexFunc glPointSizexPtr;
        private delegate void glPolygonOffsetxFunc(int factor, int units);
        private static glPolygonOffsetxFunc glPolygonOffsetxPtr;
        private delegate void glPopMatrixFunc();
        private static glPopMatrixFunc glPopMatrixPtr;
        private delegate void glPushMatrixFunc();
        private static glPushMatrixFunc glPushMatrixPtr;
        private delegate void glReadPixelsFunc(int x, int y, int width, int height, uint format, uint type, IntPtr pixels);
        private static glReadPixelsFunc glReadPixelsPtr;
        private delegate void glRotatexFunc(int angle, int x, int y, int z);
        private static glRotatexFunc glRotatexPtr;
        private delegate void glSampleCoverageFunc(float value, bool invert);
        private static glSampleCoverageFunc glSampleCoveragePtr;
        private delegate void glSampleCoveragexFunc(int value, bool invert);
        private static glSampleCoveragexFunc glSampleCoveragexPtr;
        private delegate void glScalexFunc(int x, int y, int z);
        private static glScalexFunc glScalexPtr;
        private delegate void glScissorFunc(int x, int y, int width, int height);
        private static glScissorFunc glScissorPtr;
        private delegate void glShadeModelFunc(uint mode);
        private static glShadeModelFunc glShadeModelPtr;
        private delegate void glStencilFuncFunc(uint func, int @ref, uint mask);
        private static glStencilFuncFunc glStencilFuncPtr;
        private delegate void glStencilMaskFunc(uint mask);
        private static glStencilMaskFunc glStencilMaskPtr;
        private delegate void glStencilOpFunc(uint fail, uint zfail, uint zpass);
        private static glStencilOpFunc glStencilOpPtr;
        private delegate void glTexCoordPointerFunc(int size, uint type, int stride, IntPtr pointer);
        private static glTexCoordPointerFunc glTexCoordPointerPtr;
        private delegate void glTexEnviFunc(uint target, uint pname, int param);
        private static glTexEnviFunc glTexEnviPtr;
        private delegate void glTexEnvxFunc(uint target, uint pname, int param);
        private static glTexEnvxFunc glTexEnvxPtr;
        private delegate void glTexEnvivFunc(uint target, uint pname, IntPtr @params);
        private static glTexEnvivFunc glTexEnvivPtr;
        private delegate void glTexEnvxvFunc(uint target, uint pname, IntPtr @params);
        private static glTexEnvxvFunc glTexEnvxvPtr;
        private delegate void glTexImage2DFunc(uint target, int level, int internalformat, int width, int height, int border, uint format, uint type, IntPtr pixels);
        private static glTexImage2DFunc glTexImage2DPtr;
        private delegate void glTexParameteriFunc(uint target, uint pname, int param);
        private static glTexParameteriFunc glTexParameteriPtr;
        private delegate void glTexParameterxFunc(uint target, uint pname, int param);
        private static glTexParameterxFunc glTexParameterxPtr;
        private delegate void glTexParameterivFunc(uint target, uint pname, IntPtr @params);
        private static glTexParameterivFunc glTexParameterivPtr;
        private delegate void glTexParameterxvFunc(uint target, uint pname, IntPtr @params);
        private static glTexParameterxvFunc glTexParameterxvPtr;
        private delegate void glTexSubImage2DFunc(uint target, int level, int xoffset, int yoffset, int width, int height, uint format, uint type, IntPtr pixels);
        private static glTexSubImage2DFunc glTexSubImage2DPtr;
        private delegate void glTranslatexFunc(int x, int y, int z);
        private static glTranslatexFunc glTranslatexPtr;
        private delegate void glVertexPointerFunc(int size, uint type, int stride, IntPtr pointer);
        private static glVertexPointerFunc glVertexPointerPtr;
        private delegate void glViewportFunc(int x, int y, int width, int height);
        private static glViewportFunc glViewportPtr;
        #endregion

        #region Interop
        public static Func<string, IntPtr> GetProcAddress = null;

        public static void LoadAllFunctions()
        {
            glAlphaFuncPtr = (glAlphaFuncFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glAlphaFunc"), typeof(glAlphaFuncFunc));
            glClearColorPtr = (glClearColorFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearColor"), typeof(glClearColorFunc));
            glClearDepthfPtr = (glClearDepthfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearDepthf"), typeof(glClearDepthfFunc));
            glClipPlanefPtr = (glClipPlanefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClipPlanef"), typeof(glClipPlanefFunc));
            glColor4fPtr = (glColor4fFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColor4f"), typeof(glColor4fFunc));
            glDepthRangefPtr = (glDepthRangefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDepthRangef"), typeof(glDepthRangefFunc));
            glFogfPtr = (glFogfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFogf"), typeof(glFogfFunc));
            glFogfvPtr = (glFogfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFogfv"), typeof(glFogfvFunc));
            glFrustumfPtr = (glFrustumfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFrustumf"), typeof(glFrustumfFunc));
            glGetClipPlanefPtr = (glGetClipPlanefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetClipPlanef"), typeof(glGetClipPlanefFunc));
            glGetFloatvPtr = (glGetFloatvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetFloatv"), typeof(glGetFloatvFunc));
            glGetLightfvPtr = (glGetLightfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetLightfv"), typeof(glGetLightfvFunc));
            glGetMaterialfvPtr = (glGetMaterialfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetMaterialfv"), typeof(glGetMaterialfvFunc));
            glGetTexEnvfvPtr = (glGetTexEnvfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexEnvfv"), typeof(glGetTexEnvfvFunc));
            glGetTexParameterfvPtr = (glGetTexParameterfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexParameterfv"), typeof(glGetTexParameterfvFunc));
            glLightModelfPtr = (glLightModelfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightModelf"), typeof(glLightModelfFunc));
            glLightModelfvPtr = (glLightModelfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightModelfv"), typeof(glLightModelfvFunc));
            glLightfPtr = (glLightfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightf"), typeof(glLightfFunc));
            glLightfvPtr = (glLightfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightfv"), typeof(glLightfvFunc));
            glLineWidthPtr = (glLineWidthFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLineWidth"), typeof(glLineWidthFunc));
            glLoadMatrixfPtr = (glLoadMatrixfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLoadMatrixf"), typeof(glLoadMatrixfFunc));
            glMaterialfPtr = (glMaterialfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMaterialf"), typeof(glMaterialfFunc));
            glMaterialfvPtr = (glMaterialfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMaterialfv"), typeof(glMaterialfvFunc));
            glMultMatrixfPtr = (glMultMatrixfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMultMatrixf"), typeof(glMultMatrixfFunc));
            glMultiTexCoord4fPtr = (glMultiTexCoord4fFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMultiTexCoord4f"), typeof(glMultiTexCoord4fFunc));
            glNormal3fPtr = (glNormal3fFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glNormal3f"), typeof(glNormal3fFunc));
            glOrthofPtr = (glOrthofFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glOrthof"), typeof(glOrthofFunc));
            glPointParameterfPtr = (glPointParameterfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointParameterf"), typeof(glPointParameterfFunc));
            glPointParameterfvPtr = (glPointParameterfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointParameterfv"), typeof(glPointParameterfvFunc));
            glPointSizePtr = (glPointSizeFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointSize"), typeof(glPointSizeFunc));
            glPolygonOffsetPtr = (glPolygonOffsetFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPolygonOffset"), typeof(glPolygonOffsetFunc));
            glRotatefPtr = (glRotatefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glRotatef"), typeof(glRotatefFunc));
            glScalefPtr = (glScalefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glScalef"), typeof(glScalefFunc));
            glTexEnvfPtr = (glTexEnvfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvf"), typeof(glTexEnvfFunc));
            glTexEnvfvPtr = (glTexEnvfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvfv"), typeof(glTexEnvfvFunc));
            glTexParameterfPtr = (glTexParameterfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameterf"), typeof(glTexParameterfFunc));
            glTexParameterfvPtr = (glTexParameterfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameterfv"), typeof(glTexParameterfvFunc));
            glTranslatefPtr = (glTranslatefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTranslatef"), typeof(glTranslatefFunc));
            glActiveTexturePtr = (glActiveTextureFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glActiveTexture"), typeof(glActiveTextureFunc));
            glAlphaFuncxPtr = (glAlphaFuncxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glAlphaFuncx"), typeof(glAlphaFuncxFunc));
            glBindBufferPtr = (glBindBufferFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBindBuffer"), typeof(glBindBufferFunc));
            glBindTexturePtr = (glBindTextureFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBindTexture"), typeof(glBindTextureFunc));
            glBlendFuncPtr = (glBlendFuncFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBlendFunc"), typeof(glBlendFuncFunc));
            glBufferDataPtr = (glBufferDataFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBufferData"), typeof(glBufferDataFunc));
            glBufferSubDataPtr = (glBufferSubDataFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBufferSubData"), typeof(glBufferSubDataFunc));
            glClearPtr = (glClearFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClear"), typeof(glClearFunc));
            glClearColorxPtr = (glClearColorxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearColorx"), typeof(glClearColorxFunc));
            glClearDepthxPtr = (glClearDepthxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearDepthx"), typeof(glClearDepthxFunc));
            glClearStencilPtr = (glClearStencilFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearStencil"), typeof(glClearStencilFunc));
            glClientActiveTexturePtr = (glClientActiveTextureFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClientActiveTexture"), typeof(glClientActiveTextureFunc));
            glClipPlanexPtr = (glClipPlanexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClipPlanex"), typeof(glClipPlanexFunc));
            glColor4ubPtr = (glColor4ubFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColor4ub"), typeof(glColor4ubFunc));
            glColor4xPtr = (glColor4xFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColor4x"), typeof(glColor4xFunc));
            glColorMaskPtr = (glColorMaskFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColorMask"), typeof(glColorMaskFunc));
            glColorPointerPtr = (glColorPointerFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColorPointer"), typeof(glColorPointerFunc));
            glCompressedTexImage2DPtr = (glCompressedTexImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCompressedTexImage2D"), typeof(glCompressedTexImage2DFunc));
            glCompressedTexSubImage2DPtr = (glCompressedTexSubImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCompressedTexSubImage2D"), typeof(glCompressedTexSubImage2DFunc));
            glCopyTexImage2DPtr = (glCopyTexImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCopyTexImage2D"), typeof(glCopyTexImage2DFunc));
            glCopyTexSubImage2DPtr = (glCopyTexSubImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCopyTexSubImage2D"), typeof(glCopyTexSubImage2DFunc));
            glCullFacePtr = (glCullFaceFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCullFace"), typeof(glCullFaceFunc));
            glDeleteBuffersPtr = (glDeleteBuffersFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDeleteBuffers"), typeof(glDeleteBuffersFunc));
            glDeleteTexturesPtr = (glDeleteTexturesFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDeleteTextures"), typeof(glDeleteTexturesFunc));
            glDepthFuncPtr = (glDepthFuncFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDepthFunc"), typeof(glDepthFuncFunc));
            glDepthMaskPtr = (glDepthMaskFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDepthMask"), typeof(glDepthMaskFunc));
            glDepthRangexPtr = (glDepthRangexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDepthRangex"), typeof(glDepthRangexFunc));
            glDisablePtr = (glDisableFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDisable"), typeof(glDisableFunc));
            glDisableClientStatePtr = (glDisableClientStateFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDisableClientState"), typeof(glDisableClientStateFunc));
            glDrawArraysPtr = (glDrawArraysFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDrawArrays"), typeof(glDrawArraysFunc));
            glDrawElementsPtr = (glDrawElementsFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDrawElements"), typeof(glDrawElementsFunc));
            glEnablePtr = (glEnableFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glEnable"), typeof(glEnableFunc));
            glEnableClientStatePtr = (glEnableClientStateFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glEnableClientState"), typeof(glEnableClientStateFunc));
            glFinishPtr = (glFinishFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFinish"), typeof(glFinishFunc));
            glFlushPtr = (glFlushFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFlush"), typeof(glFlushFunc));
            glFogxPtr = (glFogxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFogx"), typeof(glFogxFunc));
            glFogxvPtr = (glFogxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFogxv"), typeof(glFogxvFunc));
            glFrontFacePtr = (glFrontFaceFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFrontFace"), typeof(glFrontFaceFunc));
            glFrustumxPtr = (glFrustumxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFrustumx"), typeof(glFrustumxFunc));
            glGetBooleanvPtr = (glGetBooleanvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetBooleanv"), typeof(glGetBooleanvFunc));
            glGetBufferParameterivPtr = (glGetBufferParameterivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetBufferParameteriv"), typeof(glGetBufferParameterivFunc));
            glGetClipPlanexPtr = (glGetClipPlanexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetClipPlanex"), typeof(glGetClipPlanexFunc));
            glGenBuffersPtr = (glGenBuffersFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGenBuffers"), typeof(glGenBuffersFunc));
            glGenTexturesPtr = (glGenTexturesFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGenTextures"), typeof(glGenTexturesFunc));
            glGetErrorPtr = (glGetErrorFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetError"), typeof(glGetErrorFunc));
            glGetFixedvPtr = (glGetFixedvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetFixedv"), typeof(glGetFixedvFunc));
            glGetIntegervPtr = (glGetIntegervFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetIntegerv"), typeof(glGetIntegervFunc));
            glGetLightxvPtr = (glGetLightxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetLightxv"), typeof(glGetLightxvFunc));
            glGetMaterialxvPtr = (glGetMaterialxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetMaterialxv"), typeof(glGetMaterialxvFunc));
            glGetPointervPtr = (glGetPointervFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetPointerv"), typeof(glGetPointervFunc));
            glGetStringPtr = (glGetStringFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetString"), typeof(glGetStringFunc));
            glGetTexEnvivPtr = (glGetTexEnvivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexEnviv"), typeof(glGetTexEnvivFunc));
            glGetTexEnvxvPtr = (glGetTexEnvxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexEnvxv"), typeof(glGetTexEnvxvFunc));
            glGetTexParameterivPtr = (glGetTexParameterivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexParameteriv"), typeof(glGetTexParameterivFunc));
            glGetTexParameterxvPtr = (glGetTexParameterxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexParameterxv"), typeof(glGetTexParameterxvFunc));
            glHintPtr = (glHintFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glHint"), typeof(glHintFunc));
            glIsBufferPtr = (glIsBufferFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glIsBuffer"), typeof(glIsBufferFunc));
            glIsEnabledPtr = (glIsEnabledFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glIsEnabled"), typeof(glIsEnabledFunc));
            glIsTexturePtr = (glIsTextureFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glIsTexture"), typeof(glIsTextureFunc));
            glLightModelxPtr = (glLightModelxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightModelx"), typeof(glLightModelxFunc));
            glLightModelxvPtr = (glLightModelxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightModelxv"), typeof(glLightModelxvFunc));
            glLightxPtr = (glLightxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightx"), typeof(glLightxFunc));
            glLightxvPtr = (glLightxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightxv"), typeof(glLightxvFunc));
            glLineWidthxPtr = (glLineWidthxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLineWidthx"), typeof(glLineWidthxFunc));
            glLoadIdentityPtr = (glLoadIdentityFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLoadIdentity"), typeof(glLoadIdentityFunc));
            glLoadMatrixxPtr = (glLoadMatrixxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLoadMatrixx"), typeof(glLoadMatrixxFunc));
            glLogicOpPtr = (glLogicOpFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLogicOp"), typeof(glLogicOpFunc));
            glMaterialxPtr = (glMaterialxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMaterialx"), typeof(glMaterialxFunc));
            glMaterialxvPtr = (glMaterialxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMaterialxv"), typeof(glMaterialxvFunc));
            glMatrixModePtr = (glMatrixModeFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMatrixMode"), typeof(glMatrixModeFunc));
            glMultMatrixxPtr = (glMultMatrixxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMultMatrixx"), typeof(glMultMatrixxFunc));
            glMultiTexCoord4xPtr = (glMultiTexCoord4xFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMultiTexCoord4x"), typeof(glMultiTexCoord4xFunc));
            glNormal3xPtr = (glNormal3xFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glNormal3x"), typeof(glNormal3xFunc));
            glNormalPointerPtr = (glNormalPointerFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glNormalPointer"), typeof(glNormalPointerFunc));
            glOrthoxPtr = (glOrthoxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glOrthox"), typeof(glOrthoxFunc));
            glPixelStoreiPtr = (glPixelStoreiFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPixelStorei"), typeof(glPixelStoreiFunc));
            glPointParameterxPtr = (glPointParameterxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointParameterx"), typeof(glPointParameterxFunc));
            glPointParameterxvPtr = (glPointParameterxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointParameterxv"), typeof(glPointParameterxvFunc));
            glPointSizexPtr = (glPointSizexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointSizex"), typeof(glPointSizexFunc));
            glPolygonOffsetxPtr = (glPolygonOffsetxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPolygonOffsetx"), typeof(glPolygonOffsetxFunc));
            glPopMatrixPtr = (glPopMatrixFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPopMatrix"), typeof(glPopMatrixFunc));
            glPushMatrixPtr = (glPushMatrixFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPushMatrix"), typeof(glPushMatrixFunc));
            glReadPixelsPtr = (glReadPixelsFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glReadPixels"), typeof(glReadPixelsFunc));
            glRotatexPtr = (glRotatexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glRotatex"), typeof(glRotatexFunc));
            glSampleCoveragePtr = (glSampleCoverageFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glSampleCoverage"), typeof(glSampleCoverageFunc));
            glSampleCoveragexPtr = (glSampleCoveragexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glSampleCoveragex"), typeof(glSampleCoveragexFunc));
            glScalexPtr = (glScalexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glScalex"), typeof(glScalexFunc));
            glScissorPtr = (glScissorFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glScissor"), typeof(glScissorFunc));
            glShadeModelPtr = (glShadeModelFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glShadeModel"), typeof(glShadeModelFunc));
            glStencilFuncPtr = (glStencilFuncFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glStencilFunc"), typeof(glStencilFuncFunc));
            glStencilMaskPtr = (glStencilMaskFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glStencilMask"), typeof(glStencilMaskFunc));
            glStencilOpPtr = (glStencilOpFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glStencilOp"), typeof(glStencilOpFunc));
            glTexCoordPointerPtr = (glTexCoordPointerFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexCoordPointer"), typeof(glTexCoordPointerFunc));
            glTexEnviPtr = (glTexEnviFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvi"), typeof(glTexEnviFunc));
            glTexEnvxPtr = (glTexEnvxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvx"), typeof(glTexEnvxFunc));
            glTexEnvivPtr = (glTexEnvivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnviv"), typeof(glTexEnvivFunc));
            glTexEnvxvPtr = (glTexEnvxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvxv"), typeof(glTexEnvxvFunc));
            glTexImage2DPtr = (glTexImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexImage2D"), typeof(glTexImage2DFunc));
            glTexParameteriPtr = (glTexParameteriFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameteri"), typeof(glTexParameteriFunc));
            glTexParameterxPtr = (glTexParameterxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameterx"), typeof(glTexParameterxFunc));
            glTexParameterivPtr = (glTexParameterivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameteriv"), typeof(glTexParameterivFunc));
            glTexParameterxvPtr = (glTexParameterxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameterxv"), typeof(glTexParameterxvFunc));
            glTexSubImage2DPtr = (glTexSubImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexSubImage2D"), typeof(glTexSubImage2DFunc));
            glTranslatexPtr = (glTranslatexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTranslatex"), typeof(glTranslatexFunc));
            glVertexPointerPtr = (glVertexPointerFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glVertexPointer"), typeof(glVertexPointerFunc));
            glViewportPtr = (glViewportFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glViewport"), typeof(glViewportFunc));
        }

        public static void LoadFunction(string name)
        {
            var memberInfo = typeof(GLES10).GetField(name + "Ptr", BindingFlags.NonPublic | BindingFlags.Static);
            memberInfo.SetValue(null, Marshal.GetDelegateForFunctionPointer(GetProcAddress(name), memberInfo.FieldType));
        }
        #endregion
    }
}
