// This file was autogenerated by GLCSGen on 11/5/2013 2:29:36 PM UTC
// Original copyright from gl.xml:
// 
// Copyright (c) 2013 The Khronos Group Inc.
// 
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and/or associated documentation files (the
// "Materials"), to deal in the Materials without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Materials, and to
// permit persons to whom the Materials are furnished to do so, subject to
// the following conditions:
// 
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Materials.
// 
// THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.
// 
// ------------------------------------------------------------------------
// 
// This file, gl.xml, is the OpenGL and OpenGL API Registry. The older
// ".spec" file format has been retired and will no longer be updated with
// new extensions and API versions. The canonical version of the registry,
// together with documentation, schema, and Python generator scripts used
// to generate C header files for OpenGL and OpenGL ES, can always be found
// in the Khronos Registry at
//         http://www.opengl.org/registry/
//     

using System;
using System.Reflection;
using System.Runtime.InteropServices;

namespace OpenGL
{
    public static class GLES10
    {
        #region Enums
        public static uint GL_VERSION_ES_CL_1_0 = 1;
        public static uint GL_VERSION_ES_CM_1_1 = 1;
        public static uint GL_VERSION_ES_CL_1_1 = 1;
        public static uint GL_DEPTH_BUFFER_BIT = 0x00000100;
        public static uint GL_STENCIL_BUFFER_BIT = 0x00000400;
        public static uint GL_COLOR_BUFFER_BIT = 0x00004000;
        public static uint GL_FALSE = 0;
        public static uint GL_TRUE = 1;
        public static uint GL_POINTS = 0x0000;
        public static uint GL_LINES = 0x0001;
        public static uint GL_LINE_LOOP = 0x0002;
        public static uint GL_LINE_STRIP = 0x0003;
        public static uint GL_TRIANGLES = 0x0004;
        public static uint GL_TRIANGLE_STRIP = 0x0005;
        public static uint GL_TRIANGLE_FAN = 0x0006;
        public static uint GL_NEVER = 0x0200;
        public static uint GL_LESS = 0x0201;
        public static uint GL_EQUAL = 0x0202;
        public static uint GL_LEQUAL = 0x0203;
        public static uint GL_GREATER = 0x0204;
        public static uint GL_NOTEQUAL = 0x0205;
        public static uint GL_GEQUAL = 0x0206;
        public static uint GL_ALWAYS = 0x0207;
        public static uint GL_ZERO = 0;
        public static uint GL_ONE = 1;
        public static uint GL_SRC_COLOR = 0x0300;
        public static uint GL_ONE_MINUS_SRC_COLOR = 0x0301;
        public static uint GL_SRC_ALPHA = 0x0302;
        public static uint GL_ONE_MINUS_SRC_ALPHA = 0x0303;
        public static uint GL_DST_ALPHA = 0x0304;
        public static uint GL_ONE_MINUS_DST_ALPHA = 0x0305;
        public static uint GL_DST_COLOR = 0x0306;
        public static uint GL_ONE_MINUS_DST_COLOR = 0x0307;
        public static uint GL_SRC_ALPHA_SATURATE = 0x0308;
        public static uint GL_CLIP_PLANE0 = 0x3000;
        public static uint GL_CLIP_PLANE1 = 0x3001;
        public static uint GL_CLIP_PLANE2 = 0x3002;
        public static uint GL_CLIP_PLANE3 = 0x3003;
        public static uint GL_CLIP_PLANE4 = 0x3004;
        public static uint GL_CLIP_PLANE5 = 0x3005;
        public static uint GL_FRONT = 0x0404;
        public static uint GL_BACK = 0x0405;
        public static uint GL_FRONT_AND_BACK = 0x0408;
        public static uint GL_FOG = 0x0B60;
        public static uint GL_LIGHTING = 0x0B50;
        public static uint GL_TEXTURE_2D = 0x0DE1;
        public static uint GL_CULL_FACE = 0x0B44;
        public static uint GL_ALPHA_TEST = 0x0BC0;
        public static uint GL_BLEND = 0x0BE2;
        public static uint GL_COLOR_LOGIC_OP = 0x0BF2;
        public static uint GL_DITHER = 0x0BD0;
        public static uint GL_STENCIL_TEST = 0x0B90;
        public static uint GL_DEPTH_TEST = 0x0B71;
        public static uint GL_POINT_SMOOTH = 0x0B10;
        public static uint GL_LINE_SMOOTH = 0x0B20;
        public static uint GL_SCISSOR_TEST = 0x0C11;
        public static uint GL_COLOR_MATERIAL = 0x0B57;
        public static uint GL_NORMALIZE = 0x0BA1;
        public static uint GL_RESCALE_NORMAL = 0x803A;
        public static uint GL_VERTEX_ARRAY = 0x8074;
        public static uint GL_NORMAL_ARRAY = 0x8075;
        public static uint GL_COLOR_ARRAY = 0x8076;
        public static uint GL_TEXTURE_COORD_ARRAY = 0x8078;
        public static uint GL_MULTISAMPLE = 0x809D;
        public static uint GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
        public static uint GL_SAMPLE_ALPHA_TO_ONE = 0x809F;
        public static uint GL_SAMPLE_COVERAGE = 0x80A0;
        public static uint GL_NO_ERROR = 0;
        public static uint GL_INVALID_ENUM = 0x0500;
        public static uint GL_INVALID_VALUE = 0x0501;
        public static uint GL_INVALID_OPERATION = 0x0502;
        public static uint GL_STACK_OVERFLOW = 0x0503;
        public static uint GL_STACK_UNDERFLOW = 0x0504;
        public static uint GL_OUT_OF_MEMORY = 0x0505;
        public static uint GL_EXP = 0x0800;
        public static uint GL_EXP2 = 0x0801;
        public static uint GL_FOG_DENSITY = 0x0B62;
        public static uint GL_FOG_START = 0x0B63;
        public static uint GL_FOG_END = 0x0B64;
        public static uint GL_FOG_MODE = 0x0B65;
        public static uint GL_FOG_COLOR = 0x0B66;
        public static uint GL_CW = 0x0900;
        public static uint GL_CCW = 0x0901;
        public static uint GL_CURRENT_COLOR = 0x0B00;
        public static uint GL_CURRENT_NORMAL = 0x0B02;
        public static uint GL_CURRENT_TEXTURE_COORDS = 0x0B03;
        public static uint GL_POINT_SIZE = 0x0B11;
        public static uint GL_POINT_SIZE_MIN = 0x8126;
        public static uint GL_POINT_SIZE_MAX = 0x8127;
        public static uint GL_POINT_FADE_THRESHOLD_SIZE = 0x8128;
        public static uint GL_POINT_DISTANCE_ATTENUATION = 0x8129;
        public static uint GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12;
        public static uint GL_LINE_WIDTH = 0x0B21;
        public static uint GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22;
        public static uint GL_ALIASED_POINT_SIZE_RANGE = 0x846D;
        public static uint GL_ALIASED_LINE_WIDTH_RANGE = 0x846E;
        public static uint GL_CULL_FACE_MODE = 0x0B45;
        public static uint GL_FRONT_FACE = 0x0B46;
        public static uint GL_SHADE_MODEL = 0x0B54;
        public static uint GL_DEPTH_RANGE = 0x0B70;
        public static uint GL_DEPTH_WRITEMASK = 0x0B72;
        public static uint GL_DEPTH_CLEAR_VALUE = 0x0B73;
        public static uint GL_DEPTH_FUNC = 0x0B74;
        public static uint GL_STENCIL_CLEAR_VALUE = 0x0B91;
        public static uint GL_STENCIL_FUNC = 0x0B92;
        public static uint GL_STENCIL_VALUE_MASK = 0x0B93;
        public static uint GL_STENCIL_FAIL = 0x0B94;
        public static uint GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95;
        public static uint GL_STENCIL_PASS_DEPTH_PASS = 0x0B96;
        public static uint GL_STENCIL_REF = 0x0B97;
        public static uint GL_STENCIL_WRITEMASK = 0x0B98;
        public static uint GL_MATRIX_MODE = 0x0BA0;
        public static uint GL_VIEWPORT = 0x0BA2;
        public static uint GL_MODELVIEW_STACK_DEPTH = 0x0BA3;
        public static uint GL_PROJECTION_STACK_DEPTH = 0x0BA4;
        public static uint GL_TEXTURE_STACK_DEPTH = 0x0BA5;
        public static uint GL_MODELVIEW_MATRIX = 0x0BA6;
        public static uint GL_PROJECTION_MATRIX = 0x0BA7;
        public static uint GL_TEXTURE_MATRIX = 0x0BA8;
        public static uint GL_ALPHA_TEST_FUNC = 0x0BC1;
        public static uint GL_ALPHA_TEST_REF = 0x0BC2;
        public static uint GL_BLEND_DST = 0x0BE0;
        public static uint GL_BLEND_SRC = 0x0BE1;
        public static uint GL_LOGIC_OP_MODE = 0x0BF0;
        public static uint GL_SCISSOR_BOX = 0x0C10;
        public static uint GL_COLOR_CLEAR_VALUE = 0x0C22;
        public static uint GL_COLOR_WRITEMASK = 0x0C23;
        public static uint GL_MAX_LIGHTS = 0x0D31;
        public static uint GL_MAX_CLIP_PLANES = 0x0D32;
        public static uint GL_MAX_TEXTURE_SIZE = 0x0D33;
        public static uint GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36;
        public static uint GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38;
        public static uint GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39;
        public static uint GL_MAX_VIEWPORT_DIMS = 0x0D3A;
        public static uint GL_MAX_TEXTURE_UNITS = 0x84E2;
        public static uint GL_SUBPIXEL_BITS = 0x0D50;
        public static uint GL_RED_BITS = 0x0D52;
        public static uint GL_GREEN_BITS = 0x0D53;
        public static uint GL_BLUE_BITS = 0x0D54;
        public static uint GL_ALPHA_BITS = 0x0D55;
        public static uint GL_DEPTH_BITS = 0x0D56;
        public static uint GL_STENCIL_BITS = 0x0D57;
        public static uint GL_POLYGON_OFFSET_UNITS = 0x2A00;
        public static uint GL_POLYGON_OFFSET_FILL = 0x8037;
        public static uint GL_POLYGON_OFFSET_FACTOR = 0x8038;
        public static uint GL_TEXTURE_BINDING_2D = 0x8069;
        public static uint GL_VERTEX_ARRAY_SIZE = 0x807A;
        public static uint GL_VERTEX_ARRAY_TYPE = 0x807B;
        public static uint GL_VERTEX_ARRAY_STRIDE = 0x807C;
        public static uint GL_NORMAL_ARRAY_TYPE = 0x807E;
        public static uint GL_NORMAL_ARRAY_STRIDE = 0x807F;
        public static uint GL_COLOR_ARRAY_SIZE = 0x8081;
        public static uint GL_COLOR_ARRAY_TYPE = 0x8082;
        public static uint GL_COLOR_ARRAY_STRIDE = 0x8083;
        public static uint GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088;
        public static uint GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089;
        public static uint GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A;
        public static uint GL_VERTEX_ARRAY_POINTER = 0x808E;
        public static uint GL_NORMAL_ARRAY_POINTER = 0x808F;
        public static uint GL_COLOR_ARRAY_POINTER = 0x8090;
        public static uint GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092;
        public static uint GL_SAMPLE_BUFFERS = 0x80A8;
        public static uint GL_SAMPLES = 0x80A9;
        public static uint GL_SAMPLE_COVERAGE_VALUE = 0x80AA;
        public static uint GL_SAMPLE_COVERAGE_INVERT = 0x80AB;
        public static uint GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2;
        public static uint GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3;
        public static uint GL_DONT_CARE = 0x1100;
        public static uint GL_FASTEST = 0x1101;
        public static uint GL_NICEST = 0x1102;
        public static uint GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50;
        public static uint GL_POINT_SMOOTH_HINT = 0x0C51;
        public static uint GL_LINE_SMOOTH_HINT = 0x0C52;
        public static uint GL_FOG_HINT = 0x0C54;
        public static uint GL_GENERATE_MIPMAP_HINT = 0x8192;
        public static uint GL_LIGHT_MODEL_AMBIENT = 0x0B53;
        public static uint GL_LIGHT_MODEL_TWO_SIDE = 0x0B52;
        public static uint GL_AMBIENT = 0x1200;
        public static uint GL_DIFFUSE = 0x1201;
        public static uint GL_SPECULAR = 0x1202;
        public static uint GL_POSITION = 0x1203;
        public static uint GL_SPOT_DIRECTION = 0x1204;
        public static uint GL_SPOT_EXPONENT = 0x1205;
        public static uint GL_SPOT_CUTOFF = 0x1206;
        public static uint GL_CONSTANT_ATTENUATION = 0x1207;
        public static uint GL_LINEAR_ATTENUATION = 0x1208;
        public static uint GL_QUADRATIC_ATTENUATION = 0x1209;
        public static uint GL_BYTE = 0x1400;
        public static uint GL_UNSIGNED_BYTE = 0x1401;
        public static uint GL_SHORT = 0x1402;
        public static uint GL_UNSIGNED_SHORT = 0x1403;
        public static uint GL_FLOAT = 0x1406;
        public static uint GL_FIXED = 0x140C;
        public static uint GL_CLEAR = 0x1500;
        public static uint GL_AND = 0x1501;
        public static uint GL_AND_REVERSE = 0x1502;
        public static uint GL_COPY = 0x1503;
        public static uint GL_AND_INVERTED = 0x1504;
        public static uint GL_NOOP = 0x1505;
        public static uint GL_XOR = 0x1506;
        public static uint GL_OR = 0x1507;
        public static uint GL_NOR = 0x1508;
        public static uint GL_EQUIV = 0x1509;
        public static uint GL_INVERT = 0x150A;
        public static uint GL_OR_REVERSE = 0x150B;
        public static uint GL_COPY_INVERTED = 0x150C;
        public static uint GL_OR_INVERTED = 0x150D;
        public static uint GL_NAND = 0x150E;
        public static uint GL_SET = 0x150F;
        public static uint GL_EMISSION = 0x1600;
        public static uint GL_SHININESS = 0x1601;
        public static uint GL_AMBIENT_AND_DIFFUSE = 0x1602;
        public static uint GL_MODELVIEW = 0x1700;
        public static uint GL_PROJECTION = 0x1701;
        public static uint GL_TEXTURE = 0x1702;
        public static uint GL_ALPHA = 0x1906;
        public static uint GL_RGB = 0x1907;
        public static uint GL_RGBA = 0x1908;
        public static uint GL_LUMINANCE = 0x1909;
        public static uint GL_LUMINANCE_ALPHA = 0x190A;
        public static uint GL_UNPACK_ALIGNMENT = 0x0CF5;
        public static uint GL_PACK_ALIGNMENT = 0x0D05;
        public static uint GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033;
        public static uint GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034;
        public static uint GL_UNSIGNED_SHORT_5_6_5 = 0x8363;
        public static uint GL_FLAT = 0x1D00;
        public static uint GL_SMOOTH = 0x1D01;
        public static uint GL_KEEP = 0x1E00;
        public static uint GL_REPLACE = 0x1E01;
        public static uint GL_INCR = 0x1E02;
        public static uint GL_DECR = 0x1E03;
        public static uint GL_VENDOR = 0x1F00;
        public static uint GL_RENDERER = 0x1F01;
        public static uint GL_VERSION = 0x1F02;
        public static uint GL_EXTENSIONS = 0x1F03;
        public static uint GL_MODULATE = 0x2100;
        public static uint GL_DECAL = 0x2101;
        public static uint GL_ADD = 0x0104;
        public static uint GL_TEXTURE_ENV_MODE = 0x2200;
        public static uint GL_TEXTURE_ENV_COLOR = 0x2201;
        public static uint GL_TEXTURE_ENV = 0x2300;
        public static uint GL_NEAREST = 0x2600;
        public static uint GL_LINEAR = 0x2601;
        public static uint GL_NEAREST_MIPMAP_NEAREST = 0x2700;
        public static uint GL_LINEAR_MIPMAP_NEAREST = 0x2701;
        public static uint GL_NEAREST_MIPMAP_LINEAR = 0x2702;
        public static uint GL_LINEAR_MIPMAP_LINEAR = 0x2703;
        public static uint GL_TEXTURE_MAG_FILTER = 0x2800;
        public static uint GL_TEXTURE_MIN_FILTER = 0x2801;
        public static uint GL_TEXTURE_WRAP_S = 0x2802;
        public static uint GL_TEXTURE_WRAP_T = 0x2803;
        public static uint GL_GENERATE_MIPMAP = 0x8191;
        public static uint GL_TEXTURE0 = 0x84C0;
        public static uint GL_TEXTURE1 = 0x84C1;
        public static uint GL_TEXTURE2 = 0x84C2;
        public static uint GL_TEXTURE3 = 0x84C3;
        public static uint GL_TEXTURE4 = 0x84C4;
        public static uint GL_TEXTURE5 = 0x84C5;
        public static uint GL_TEXTURE6 = 0x84C6;
        public static uint GL_TEXTURE7 = 0x84C7;
        public static uint GL_TEXTURE8 = 0x84C8;
        public static uint GL_TEXTURE9 = 0x84C9;
        public static uint GL_TEXTURE10 = 0x84CA;
        public static uint GL_TEXTURE11 = 0x84CB;
        public static uint GL_TEXTURE12 = 0x84CC;
        public static uint GL_TEXTURE13 = 0x84CD;
        public static uint GL_TEXTURE14 = 0x84CE;
        public static uint GL_TEXTURE15 = 0x84CF;
        public static uint GL_TEXTURE16 = 0x84D0;
        public static uint GL_TEXTURE17 = 0x84D1;
        public static uint GL_TEXTURE18 = 0x84D2;
        public static uint GL_TEXTURE19 = 0x84D3;
        public static uint GL_TEXTURE20 = 0x84D4;
        public static uint GL_TEXTURE21 = 0x84D5;
        public static uint GL_TEXTURE22 = 0x84D6;
        public static uint GL_TEXTURE23 = 0x84D7;
        public static uint GL_TEXTURE24 = 0x84D8;
        public static uint GL_TEXTURE25 = 0x84D9;
        public static uint GL_TEXTURE26 = 0x84DA;
        public static uint GL_TEXTURE27 = 0x84DB;
        public static uint GL_TEXTURE28 = 0x84DC;
        public static uint GL_TEXTURE29 = 0x84DD;
        public static uint GL_TEXTURE30 = 0x84DE;
        public static uint GL_TEXTURE31 = 0x84DF;
        public static uint GL_ACTIVE_TEXTURE = 0x84E0;
        public static uint GL_CLIENT_ACTIVE_TEXTURE = 0x84E1;
        public static uint GL_REPEAT = 0x2901;
        public static uint GL_CLAMP_TO_EDGE = 0x812F;
        public static uint GL_LIGHT0 = 0x4000;
        public static uint GL_LIGHT1 = 0x4001;
        public static uint GL_LIGHT2 = 0x4002;
        public static uint GL_LIGHT3 = 0x4003;
        public static uint GL_LIGHT4 = 0x4004;
        public static uint GL_LIGHT5 = 0x4005;
        public static uint GL_LIGHT6 = 0x4006;
        public static uint GL_LIGHT7 = 0x4007;
        public static uint GL_ARRAY_BUFFER = 0x8892;
        public static uint GL_ELEMENT_ARRAY_BUFFER = 0x8893;
        public static uint GL_ARRAY_BUFFER_BINDING = 0x8894;
        public static uint GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895;
        public static uint GL_VERTEX_ARRAY_BUFFER_BINDING = 0x8896;
        public static uint GL_NORMAL_ARRAY_BUFFER_BINDING = 0x8897;
        public static uint GL_COLOR_ARRAY_BUFFER_BINDING = 0x8898;
        public static uint GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A;
        public static uint GL_STATIC_DRAW = 0x88E4;
        public static uint GL_DYNAMIC_DRAW = 0x88E8;
        public static uint GL_BUFFER_SIZE = 0x8764;
        public static uint GL_BUFFER_USAGE = 0x8765;
        public static uint GL_SUBTRACT = 0x84E7;
        public static uint GL_COMBINE = 0x8570;
        public static uint GL_COMBINE_RGB = 0x8571;
        public static uint GL_COMBINE_ALPHA = 0x8572;
        public static uint GL_RGB_SCALE = 0x8573;
        public static uint GL_ADD_SIGNED = 0x8574;
        public static uint GL_INTERPOLATE = 0x8575;
        public static uint GL_CONSTANT = 0x8576;
        public static uint GL_PRIMARY_COLOR = 0x8577;
        public static uint GL_PREVIOUS = 0x8578;
        public static uint GL_OPERAND0_RGB = 0x8590;
        public static uint GL_OPERAND1_RGB = 0x8591;
        public static uint GL_OPERAND2_RGB = 0x8592;
        public static uint GL_OPERAND0_ALPHA = 0x8598;
        public static uint GL_OPERAND1_ALPHA = 0x8599;
        public static uint GL_OPERAND2_ALPHA = 0x859A;
        public static uint GL_ALPHA_SCALE = 0x0D1C;
        public static uint GL_SRC0_RGB = 0x8580;
        public static uint GL_SRC1_RGB = 0x8581;
        public static uint GL_SRC2_RGB = 0x8582;
        public static uint GL_SRC0_ALPHA = 0x8588;
        public static uint GL_SRC1_ALPHA = 0x8589;
        public static uint GL_SRC2_ALPHA = 0x858A;
        public static uint GL_DOT3_RGB = 0x86AE;
        public static uint GL_DOT3_RGBA = 0x86AF;
        #endregion

        #region Commands
        public static void glAlphaFunc(uint func, float @ref)
        {
            GLESInterop.glAlphaFuncPtr(func, @ref);
        }
        public static void glClearColor(float red, float green, float blue, float alpha)
        {
            GLESInterop.glClearColorPtr(red, green, blue, alpha);
        }
        public static void glClearDepthf(float d)
        {
            GLESInterop.glClearDepthfPtr(d);
        }
        public static void glClipPlanef(uint p, IntPtr eqn)
        {
            GLESInterop.glClipPlanefPtr(p, eqn);
        }
        public static void glColor4f(float red, float green, float blue, float alpha)
        {
            GLESInterop.glColor4fPtr(red, green, blue, alpha);
        }
        public static void glDepthRangef(float n, float f)
        {
            GLESInterop.glDepthRangefPtr(n, f);
        }
        public static void glFogf(uint pname, float param)
        {
            GLESInterop.glFogfPtr(pname, param);
        }
        public static void glFogfv(uint pname, IntPtr @params)
        {
            GLESInterop.glFogfvPtr(pname, @params);
        }
        public static void glFrustumf(float l, float r, float b, float t, float n, float f)
        {
            GLESInterop.glFrustumfPtr(l, r, b, t, n, f);
        }
        public static void glGetClipPlanef(uint plane, IntPtr equation)
        {
            GLESInterop.glGetClipPlanefPtr(plane, equation);
        }
        public static void glGetFloatv(uint pname, IntPtr data)
        {
            GLESInterop.glGetFloatvPtr(pname, data);
        }
        public static void glGetLightfv(uint light, uint pname, IntPtr @params)
        {
            GLESInterop.glGetLightfvPtr(light, pname, @params);
        }
        public static void glGetMaterialfv(uint face, uint pname, IntPtr @params)
        {
            GLESInterop.glGetMaterialfvPtr(face, pname, @params);
        }
        public static void glGetTexEnvfv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glGetTexEnvfvPtr(target, pname, @params);
        }
        public static void glGetTexParameterfv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glGetTexParameterfvPtr(target, pname, @params);
        }
        public static void glLightModelf(uint pname, float param)
        {
            GLESInterop.glLightModelfPtr(pname, param);
        }
        public static void glLightModelfv(uint pname, IntPtr @params)
        {
            GLESInterop.glLightModelfvPtr(pname, @params);
        }
        public static void glLightf(uint light, uint pname, float param)
        {
            GLESInterop.glLightfPtr(light, pname, param);
        }
        public static void glLightfv(uint light, uint pname, IntPtr @params)
        {
            GLESInterop.glLightfvPtr(light, pname, @params);
        }
        public static void glLineWidth(float width)
        {
            GLESInterop.glLineWidthPtr(width);
        }
        public static void glLoadMatrixf(IntPtr m)
        {
            GLESInterop.glLoadMatrixfPtr(m);
        }
        public static void glMaterialf(uint face, uint pname, float param)
        {
            GLESInterop.glMaterialfPtr(face, pname, param);
        }
        public static void glMaterialfv(uint face, uint pname, IntPtr @params)
        {
            GLESInterop.glMaterialfvPtr(face, pname, @params);
        }
        public static void glMultMatrixf(IntPtr m)
        {
            GLESInterop.glMultMatrixfPtr(m);
        }
        public static void glMultiTexCoord4f(uint target, float s, float t, float r, float q)
        {
            GLESInterop.glMultiTexCoord4fPtr(target, s, t, r, q);
        }
        public static void glNormal3f(float nx, float ny, float nz)
        {
            GLESInterop.glNormal3fPtr(nx, ny, nz);
        }
        public static void glOrthof(float l, float r, float b, float t, float n, float f)
        {
            GLESInterop.glOrthofPtr(l, r, b, t, n, f);
        }
        public static void glPointParameterf(uint pname, float param)
        {
            GLESInterop.glPointParameterfPtr(pname, param);
        }
        public static void glPointParameterfv(uint pname, IntPtr @params)
        {
            GLESInterop.glPointParameterfvPtr(pname, @params);
        }
        public static void glPointSize(float size)
        {
            GLESInterop.glPointSizePtr(size);
        }
        public static void glPolygonOffset(float factor, float units)
        {
            GLESInterop.glPolygonOffsetPtr(factor, units);
        }
        public static void glRotatef(float angle, float x, float y, float z)
        {
            GLESInterop.glRotatefPtr(angle, x, y, z);
        }
        public static void glScalef(float x, float y, float z)
        {
            GLESInterop.glScalefPtr(x, y, z);
        }
        public static void glTexEnvf(uint target, uint pname, float param)
        {
            GLESInterop.glTexEnvfPtr(target, pname, param);
        }
        public static void glTexEnvfv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glTexEnvfvPtr(target, pname, @params);
        }
        public static void glTexParameterf(uint target, uint pname, float param)
        {
            GLESInterop.glTexParameterfPtr(target, pname, param);
        }
        public static void glTexParameterfv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glTexParameterfvPtr(target, pname, @params);
        }
        public static void glTranslatef(float x, float y, float z)
        {
            GLESInterop.glTranslatefPtr(x, y, z);
        }
        public static void glActiveTexture(uint texture)
        {
            GLESInterop.glActiveTexturePtr(texture);
        }
        public static void glAlphaFuncx(uint func, int @ref)
        {
            GLESInterop.glAlphaFuncxPtr(func, @ref);
        }
        public static void glBindBuffer(uint target, uint buffer)
        {
            GLESInterop.glBindBufferPtr(target, buffer);
        }
        public static void glBindTexture(uint target, uint texture)
        {
            GLESInterop.glBindTexturePtr(target, texture);
        }
        public static void glBlendFunc(uint sfactor, uint dfactor)
        {
            GLESInterop.glBlendFuncPtr(sfactor, dfactor);
        }
        public static void glBufferData(uint target, int size, IntPtr data, uint usage)
        {
            GLESInterop.glBufferDataPtr(target, size, data, usage);
        }
        public static void glBufferSubData(uint target, IntPtr offset, int size, IntPtr data)
        {
            GLESInterop.glBufferSubDataPtr(target, offset, size, data);
        }
        public static void glClear(uint mask)
        {
            GLESInterop.glClearPtr(mask);
        }
        public static void glClearColorx(int red, int green, int blue, int alpha)
        {
            GLESInterop.glClearColorxPtr(red, green, blue, alpha);
        }
        public static void glClearDepthx(int depth)
        {
            GLESInterop.glClearDepthxPtr(depth);
        }
        public static void glClearStencil(int s)
        {
            GLESInterop.glClearStencilPtr(s);
        }
        public static void glClientActiveTexture(uint texture)
        {
            GLESInterop.glClientActiveTexturePtr(texture);
        }
        public static void glClipPlanex(uint plane, IntPtr equation)
        {
            GLESInterop.glClipPlanexPtr(plane, equation);
        }
        public static void glColor4ub(byte red, byte green, byte blue, byte alpha)
        {
            GLESInterop.glColor4ubPtr(red, green, blue, alpha);
        }
        public static void glColor4x(int red, int green, int blue, int alpha)
        {
            GLESInterop.glColor4xPtr(red, green, blue, alpha);
        }
        public static void glColorMask(bool red, bool green, bool blue, bool alpha)
        {
            GLESInterop.glColorMaskPtr(red, green, blue, alpha);
        }
        public static void glColorPointer(int size, uint type, int stride, IntPtr pointer)
        {
            GLESInterop.glColorPointerPtr(size, type, stride, pointer);
        }
        public static void glCompressedTexImage2D(uint target, int level, uint internalformat, int width, int height, int border, int imageSize, IntPtr data)
        {
            GLESInterop.glCompressedTexImage2DPtr(target, level, internalformat, width, height, border, imageSize, data);
        }
        public static void glCompressedTexSubImage2D(uint target, int level, int xoffset, int yoffset, int width, int height, uint format, int imageSize, IntPtr data)
        {
            GLESInterop.glCompressedTexSubImage2DPtr(target, level, xoffset, yoffset, width, height, format, imageSize, data);
        }
        public static void glCopyTexImage2D(uint target, int level, uint internalformat, int x, int y, int width, int height, int border)
        {
            GLESInterop.glCopyTexImage2DPtr(target, level, internalformat, x, y, width, height, border);
        }
        public static void glCopyTexSubImage2D(uint target, int level, int xoffset, int yoffset, int x, int y, int width, int height)
        {
            GLESInterop.glCopyTexSubImage2DPtr(target, level, xoffset, yoffset, x, y, width, height);
        }
        public static void glCullFace(uint mode)
        {
            GLESInterop.glCullFacePtr(mode);
        }
        public static void glDeleteBuffers(int n, IntPtr buffers)
        {
            GLESInterop.glDeleteBuffersPtr(n, buffers);
        }
        public static void glDeleteTextures(int n, IntPtr textures)
        {
            GLESInterop.glDeleteTexturesPtr(n, textures);
        }
        public static void glDepthFunc(uint func)
        {
            GLESInterop.glDepthFuncPtr(func);
        }
        public static void glDepthMask(bool flag)
        {
            GLESInterop.glDepthMaskPtr(flag);
        }
        public static void glDepthRangex(int n, int f)
        {
            GLESInterop.glDepthRangexPtr(n, f);
        }
        public static void glDisable(uint cap)
        {
            GLESInterop.glDisablePtr(cap);
        }
        public static void glDisableClientState(uint array)
        {
            GLESInterop.glDisableClientStatePtr(array);
        }
        public static void glDrawArrays(uint mode, int first, int count)
        {
            GLESInterop.glDrawArraysPtr(mode, first, count);
        }
        public static void glDrawElements(uint mode, int count, uint type, IntPtr indices)
        {
            GLESInterop.glDrawElementsPtr(mode, count, type, indices);
        }
        public static void glEnable(uint cap)
        {
            GLESInterop.glEnablePtr(cap);
        }
        public static void glEnableClientState(uint array)
        {
            GLESInterop.glEnableClientStatePtr(array);
        }
        public static void glFinish()
        {
            GLESInterop.glFinishPtr();
        }
        public static void glFlush()
        {
            GLESInterop.glFlushPtr();
        }
        public static void glFogx(uint pname, int param)
        {
            GLESInterop.glFogxPtr(pname, param);
        }
        public static void glFogxv(uint pname, IntPtr param)
        {
            GLESInterop.glFogxvPtr(pname, param);
        }
        public static void glFrontFace(uint mode)
        {
            GLESInterop.glFrontFacePtr(mode);
        }
        public static void glFrustumx(int l, int r, int b, int t, int n, int f)
        {
            GLESInterop.glFrustumxPtr(l, r, b, t, n, f);
        }
        public static void glGetBooleanv(uint pname, IntPtr data)
        {
            GLESInterop.glGetBooleanvPtr(pname, data);
        }
        public static void glGetBufferParameteriv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glGetBufferParameterivPtr(target, pname, @params);
        }
        public static void glGetClipPlanex(uint plane, IntPtr equation)
        {
            GLESInterop.glGetClipPlanexPtr(plane, equation);
        }
        public static void glGenBuffers(int n, IntPtr buffers)
        {
            GLESInterop.glGenBuffersPtr(n, buffers);
        }
        public static void glGenTextures(int n, IntPtr textures)
        {
            GLESInterop.glGenTexturesPtr(n, textures);
        }
        public static uint glGetError()
        {
            return GLESInterop.glGetErrorPtr();
        }
        public static void glGetFixedv(uint pname, IntPtr @params)
        {
            GLESInterop.glGetFixedvPtr(pname, @params);
        }
        public static void glGetIntegerv(uint pname, IntPtr data)
        {
            GLESInterop.glGetIntegervPtr(pname, data);
        }
        public static void glGetLightxv(uint light, uint pname, IntPtr @params)
        {
            GLESInterop.glGetLightxvPtr(light, pname, @params);
        }
        public static void glGetMaterialxv(uint face, uint pname, IntPtr @params)
        {
            GLESInterop.glGetMaterialxvPtr(face, pname, @params);
        }
        public static void glGetPointerv(uint pname, IntPtr @params)
        {
            GLESInterop.glGetPointervPtr(pname, @params);
        }
        public static IntPtr glGetString(uint name)
        {
            return GLESInterop.glGetStringPtr(name);
        }
        public static void glGetTexEnviv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glGetTexEnvivPtr(target, pname, @params);
        }
        public static void glGetTexEnvxv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glGetTexEnvxvPtr(target, pname, @params);
        }
        public static void glGetTexParameteriv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glGetTexParameterivPtr(target, pname, @params);
        }
        public static void glGetTexParameterxv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glGetTexParameterxvPtr(target, pname, @params);
        }
        public static void glHint(uint target, uint mode)
        {
            GLESInterop.glHintPtr(target, mode);
        }
        public static bool glIsBuffer(uint buffer)
        {
            return GLESInterop.glIsBufferPtr(buffer);
        }
        public static bool glIsEnabled(uint cap)
        {
            return GLESInterop.glIsEnabledPtr(cap);
        }
        public static bool glIsTexture(uint texture)
        {
            return GLESInterop.glIsTexturePtr(texture);
        }
        public static void glLightModelx(uint pname, int param)
        {
            GLESInterop.glLightModelxPtr(pname, param);
        }
        public static void glLightModelxv(uint pname, IntPtr param)
        {
            GLESInterop.glLightModelxvPtr(pname, param);
        }
        public static void glLightx(uint light, uint pname, int param)
        {
            GLESInterop.glLightxPtr(light, pname, param);
        }
        public static void glLightxv(uint light, uint pname, IntPtr @params)
        {
            GLESInterop.glLightxvPtr(light, pname, @params);
        }
        public static void glLineWidthx(int width)
        {
            GLESInterop.glLineWidthxPtr(width);
        }
        public static void glLoadIdentity()
        {
            GLESInterop.glLoadIdentityPtr();
        }
        public static void glLoadMatrixx(IntPtr m)
        {
            GLESInterop.glLoadMatrixxPtr(m);
        }
        public static void glLogicOp(uint opcode)
        {
            GLESInterop.glLogicOpPtr(opcode);
        }
        public static void glMaterialx(uint face, uint pname, int param)
        {
            GLESInterop.glMaterialxPtr(face, pname, param);
        }
        public static void glMaterialxv(uint face, uint pname, IntPtr param)
        {
            GLESInterop.glMaterialxvPtr(face, pname, param);
        }
        public static void glMatrixMode(uint mode)
        {
            GLESInterop.glMatrixModePtr(mode);
        }
        public static void glMultMatrixx(IntPtr m)
        {
            GLESInterop.glMultMatrixxPtr(m);
        }
        public static void glMultiTexCoord4x(uint texture, int s, int t, int r, int q)
        {
            GLESInterop.glMultiTexCoord4xPtr(texture, s, t, r, q);
        }
        public static void glNormal3x(int nx, int ny, int nz)
        {
            GLESInterop.glNormal3xPtr(nx, ny, nz);
        }
        public static void glNormalPointer(uint type, int stride, IntPtr pointer)
        {
            GLESInterop.glNormalPointerPtr(type, stride, pointer);
        }
        public static void glOrthox(int l, int r, int b, int t, int n, int f)
        {
            GLESInterop.glOrthoxPtr(l, r, b, t, n, f);
        }
        public static void glPixelStorei(uint pname, int param)
        {
            GLESInterop.glPixelStoreiPtr(pname, param);
        }
        public static void glPointParameterx(uint pname, int param)
        {
            GLESInterop.glPointParameterxPtr(pname, param);
        }
        public static void glPointParameterxv(uint pname, IntPtr @params)
        {
            GLESInterop.glPointParameterxvPtr(pname, @params);
        }
        public static void glPointSizex(int size)
        {
            GLESInterop.glPointSizexPtr(size);
        }
        public static void glPolygonOffsetx(int factor, int units)
        {
            GLESInterop.glPolygonOffsetxPtr(factor, units);
        }
        public static void glPopMatrix()
        {
            GLESInterop.glPopMatrixPtr();
        }
        public static void glPushMatrix()
        {
            GLESInterop.glPushMatrixPtr();
        }
        public static void glReadPixels(int x, int y, int width, int height, uint format, uint type, IntPtr pixels)
        {
            GLESInterop.glReadPixelsPtr(x, y, width, height, format, type, pixels);
        }
        public static void glRotatex(int angle, int x, int y, int z)
        {
            GLESInterop.glRotatexPtr(angle, x, y, z);
        }
        public static void glSampleCoverage(float value, bool invert)
        {
            GLESInterop.glSampleCoveragePtr(value, invert);
        }
        public static void glSampleCoveragex(int value, bool invert)
        {
            GLESInterop.glSampleCoveragexPtr(value, invert);
        }
        public static void glScalex(int x, int y, int z)
        {
            GLESInterop.glScalexPtr(x, y, z);
        }
        public static void glScissor(int x, int y, int width, int height)
        {
            GLESInterop.glScissorPtr(x, y, width, height);
        }
        public static void glShadeModel(uint mode)
        {
            GLESInterop.glShadeModelPtr(mode);
        }
        public static void glStencilFunc(uint func, int @ref, uint mask)
        {
            GLESInterop.glStencilFuncPtr(func, @ref, mask);
        }
        public static void glStencilMask(uint mask)
        {
            GLESInterop.glStencilMaskPtr(mask);
        }
        public static void glStencilOp(uint fail, uint zfail, uint zpass)
        {
            GLESInterop.glStencilOpPtr(fail, zfail, zpass);
        }
        public static void glTexCoordPointer(int size, uint type, int stride, IntPtr pointer)
        {
            GLESInterop.glTexCoordPointerPtr(size, type, stride, pointer);
        }
        public static void glTexEnvi(uint target, uint pname, int param)
        {
            GLESInterop.glTexEnviPtr(target, pname, param);
        }
        public static void glTexEnvx(uint target, uint pname, int param)
        {
            GLESInterop.glTexEnvxPtr(target, pname, param);
        }
        public static void glTexEnviv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glTexEnvivPtr(target, pname, @params);
        }
        public static void glTexEnvxv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glTexEnvxvPtr(target, pname, @params);
        }
        public static void glTexImage2D(uint target, int level, int internalformat, int width, int height, int border, uint format, uint type, IntPtr pixels)
        {
            GLESInterop.glTexImage2DPtr(target, level, internalformat, width, height, border, format, type, pixels);
        }
        public static void glTexParameteri(uint target, uint pname, int param)
        {
            GLESInterop.glTexParameteriPtr(target, pname, param);
        }
        public static void glTexParameterx(uint target, uint pname, int param)
        {
            GLESInterop.glTexParameterxPtr(target, pname, param);
        }
        public static void glTexParameteriv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glTexParameterivPtr(target, pname, @params);
        }
        public static void glTexParameterxv(uint target, uint pname, IntPtr @params)
        {
            GLESInterop.glTexParameterxvPtr(target, pname, @params);
        }
        public static void glTexSubImage2D(uint target, int level, int xoffset, int yoffset, int width, int height, uint format, uint type, IntPtr pixels)
        {
            GLESInterop.glTexSubImage2DPtr(target, level, xoffset, yoffset, width, height, format, type, pixels);
        }
        public static void glTranslatex(int x, int y, int z)
        {
            GLESInterop.glTranslatexPtr(x, y, z);
        }
        public static void glVertexPointer(int size, uint type, int stride, IntPtr pointer)
        {
            GLESInterop.glVertexPointerPtr(size, type, stride, pointer);
        }
        public static void glViewport(int x, int y, int width, int height)
        {
            GLESInterop.glViewportPtr(x, y, width, height);
        }
        #endregion

        #region Interop
        public static Func<string, IntPtr> GetProcAddress = null;

        public static void LoadAllFunctions()
        {
            GLESInterop.glAlphaFuncPtr = (GLESInterop.glAlphaFuncFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glAlphaFunc"), typeof(GLESInterop.glAlphaFuncFunc));
            GLESInterop.glClearColorPtr = (GLESInterop.glClearColorFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearColor"), typeof(GLESInterop.glClearColorFunc));
            GLESInterop.glClearDepthfPtr = (GLESInterop.glClearDepthfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearDepthf"), typeof(GLESInterop.glClearDepthfFunc));
            GLESInterop.glClipPlanefPtr = (GLESInterop.glClipPlanefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClipPlanef"), typeof(GLESInterop.glClipPlanefFunc));
            GLESInterop.glColor4fPtr = (GLESInterop.glColor4fFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColor4f"), typeof(GLESInterop.glColor4fFunc));
            GLESInterop.glDepthRangefPtr = (GLESInterop.glDepthRangefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDepthRangef"), typeof(GLESInterop.glDepthRangefFunc));
            GLESInterop.glFogfPtr = (GLESInterop.glFogfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFogf"), typeof(GLESInterop.glFogfFunc));
            GLESInterop.glFogfvPtr = (GLESInterop.glFogfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFogfv"), typeof(GLESInterop.glFogfvFunc));
            GLESInterop.glFrustumfPtr = (GLESInterop.glFrustumfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFrustumf"), typeof(GLESInterop.glFrustumfFunc));
            GLESInterop.glGetClipPlanefPtr = (GLESInterop.glGetClipPlanefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetClipPlanef"), typeof(GLESInterop.glGetClipPlanefFunc));
            GLESInterop.glGetFloatvPtr = (GLESInterop.glGetFloatvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetFloatv"), typeof(GLESInterop.glGetFloatvFunc));
            GLESInterop.glGetLightfvPtr = (GLESInterop.glGetLightfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetLightfv"), typeof(GLESInterop.glGetLightfvFunc));
            GLESInterop.glGetMaterialfvPtr = (GLESInterop.glGetMaterialfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetMaterialfv"), typeof(GLESInterop.glGetMaterialfvFunc));
            GLESInterop.glGetTexEnvfvPtr = (GLESInterop.glGetTexEnvfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexEnvfv"), typeof(GLESInterop.glGetTexEnvfvFunc));
            GLESInterop.glGetTexParameterfvPtr = (GLESInterop.glGetTexParameterfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexParameterfv"), typeof(GLESInterop.glGetTexParameterfvFunc));
            GLESInterop.glLightModelfPtr = (GLESInterop.glLightModelfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightModelf"), typeof(GLESInterop.glLightModelfFunc));
            GLESInterop.glLightModelfvPtr = (GLESInterop.glLightModelfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightModelfv"), typeof(GLESInterop.glLightModelfvFunc));
            GLESInterop.glLightfPtr = (GLESInterop.glLightfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightf"), typeof(GLESInterop.glLightfFunc));
            GLESInterop.glLightfvPtr = (GLESInterop.glLightfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightfv"), typeof(GLESInterop.glLightfvFunc));
            GLESInterop.glLineWidthPtr = (GLESInterop.glLineWidthFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLineWidth"), typeof(GLESInterop.glLineWidthFunc));
            GLESInterop.glLoadMatrixfPtr = (GLESInterop.glLoadMatrixfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLoadMatrixf"), typeof(GLESInterop.glLoadMatrixfFunc));
            GLESInterop.glMaterialfPtr = (GLESInterop.glMaterialfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMaterialf"), typeof(GLESInterop.glMaterialfFunc));
            GLESInterop.glMaterialfvPtr = (GLESInterop.glMaterialfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMaterialfv"), typeof(GLESInterop.glMaterialfvFunc));
            GLESInterop.glMultMatrixfPtr = (GLESInterop.glMultMatrixfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMultMatrixf"), typeof(GLESInterop.glMultMatrixfFunc));
            GLESInterop.glMultiTexCoord4fPtr = (GLESInterop.glMultiTexCoord4fFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMultiTexCoord4f"), typeof(GLESInterop.glMultiTexCoord4fFunc));
            GLESInterop.glNormal3fPtr = (GLESInterop.glNormal3fFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glNormal3f"), typeof(GLESInterop.glNormal3fFunc));
            GLESInterop.glOrthofPtr = (GLESInterop.glOrthofFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glOrthof"), typeof(GLESInterop.glOrthofFunc));
            GLESInterop.glPointParameterfPtr = (GLESInterop.glPointParameterfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointParameterf"), typeof(GLESInterop.glPointParameterfFunc));
            GLESInterop.glPointParameterfvPtr = (GLESInterop.glPointParameterfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointParameterfv"), typeof(GLESInterop.glPointParameterfvFunc));
            GLESInterop.glPointSizePtr = (GLESInterop.glPointSizeFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointSize"), typeof(GLESInterop.glPointSizeFunc));
            GLESInterop.glPolygonOffsetPtr = (GLESInterop.glPolygonOffsetFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPolygonOffset"), typeof(GLESInterop.glPolygonOffsetFunc));
            GLESInterop.glRotatefPtr = (GLESInterop.glRotatefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glRotatef"), typeof(GLESInterop.glRotatefFunc));
            GLESInterop.glScalefPtr = (GLESInterop.glScalefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glScalef"), typeof(GLESInterop.glScalefFunc));
            GLESInterop.glTexEnvfPtr = (GLESInterop.glTexEnvfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvf"), typeof(GLESInterop.glTexEnvfFunc));
            GLESInterop.glTexEnvfvPtr = (GLESInterop.glTexEnvfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvfv"), typeof(GLESInterop.glTexEnvfvFunc));
            GLESInterop.glTexParameterfPtr = (GLESInterop.glTexParameterfFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameterf"), typeof(GLESInterop.glTexParameterfFunc));
            GLESInterop.glTexParameterfvPtr = (GLESInterop.glTexParameterfvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameterfv"), typeof(GLESInterop.glTexParameterfvFunc));
            GLESInterop.glTranslatefPtr = (GLESInterop.glTranslatefFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTranslatef"), typeof(GLESInterop.glTranslatefFunc));
            GLESInterop.glActiveTexturePtr = (GLESInterop.glActiveTextureFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glActiveTexture"), typeof(GLESInterop.glActiveTextureFunc));
            GLESInterop.glAlphaFuncxPtr = (GLESInterop.glAlphaFuncxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glAlphaFuncx"), typeof(GLESInterop.glAlphaFuncxFunc));
            GLESInterop.glBindBufferPtr = (GLESInterop.glBindBufferFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBindBuffer"), typeof(GLESInterop.glBindBufferFunc));
            GLESInterop.glBindTexturePtr = (GLESInterop.glBindTextureFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBindTexture"), typeof(GLESInterop.glBindTextureFunc));
            GLESInterop.glBlendFuncPtr = (GLESInterop.glBlendFuncFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBlendFunc"), typeof(GLESInterop.glBlendFuncFunc));
            GLESInterop.glBufferDataPtr = (GLESInterop.glBufferDataFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBufferData"), typeof(GLESInterop.glBufferDataFunc));
            GLESInterop.glBufferSubDataPtr = (GLESInterop.glBufferSubDataFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glBufferSubData"), typeof(GLESInterop.glBufferSubDataFunc));
            GLESInterop.glClearPtr = (GLESInterop.glClearFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClear"), typeof(GLESInterop.glClearFunc));
            GLESInterop.glClearColorxPtr = (GLESInterop.glClearColorxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearColorx"), typeof(GLESInterop.glClearColorxFunc));
            GLESInterop.glClearDepthxPtr = (GLESInterop.glClearDepthxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearDepthx"), typeof(GLESInterop.glClearDepthxFunc));
            GLESInterop.glClearStencilPtr = (GLESInterop.glClearStencilFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClearStencil"), typeof(GLESInterop.glClearStencilFunc));
            GLESInterop.glClientActiveTexturePtr = (GLESInterop.glClientActiveTextureFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClientActiveTexture"), typeof(GLESInterop.glClientActiveTextureFunc));
            GLESInterop.glClipPlanexPtr = (GLESInterop.glClipPlanexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glClipPlanex"), typeof(GLESInterop.glClipPlanexFunc));
            GLESInterop.glColor4ubPtr = (GLESInterop.glColor4ubFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColor4ub"), typeof(GLESInterop.glColor4ubFunc));
            GLESInterop.glColor4xPtr = (GLESInterop.glColor4xFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColor4x"), typeof(GLESInterop.glColor4xFunc));
            GLESInterop.glColorMaskPtr = (GLESInterop.glColorMaskFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColorMask"), typeof(GLESInterop.glColorMaskFunc));
            GLESInterop.glColorPointerPtr = (GLESInterop.glColorPointerFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glColorPointer"), typeof(GLESInterop.glColorPointerFunc));
            GLESInterop.glCompressedTexImage2DPtr = (GLESInterop.glCompressedTexImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCompressedTexImage2D"), typeof(GLESInterop.glCompressedTexImage2DFunc));
            GLESInterop.glCompressedTexSubImage2DPtr = (GLESInterop.glCompressedTexSubImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCompressedTexSubImage2D"), typeof(GLESInterop.glCompressedTexSubImage2DFunc));
            GLESInterop.glCopyTexImage2DPtr = (GLESInterop.glCopyTexImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCopyTexImage2D"), typeof(GLESInterop.glCopyTexImage2DFunc));
            GLESInterop.glCopyTexSubImage2DPtr = (GLESInterop.glCopyTexSubImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCopyTexSubImage2D"), typeof(GLESInterop.glCopyTexSubImage2DFunc));
            GLESInterop.glCullFacePtr = (GLESInterop.glCullFaceFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glCullFace"), typeof(GLESInterop.glCullFaceFunc));
            GLESInterop.glDeleteBuffersPtr = (GLESInterop.glDeleteBuffersFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDeleteBuffers"), typeof(GLESInterop.glDeleteBuffersFunc));
            GLESInterop.glDeleteTexturesPtr = (GLESInterop.glDeleteTexturesFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDeleteTextures"), typeof(GLESInterop.glDeleteTexturesFunc));
            GLESInterop.glDepthFuncPtr = (GLESInterop.glDepthFuncFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDepthFunc"), typeof(GLESInterop.glDepthFuncFunc));
            GLESInterop.glDepthMaskPtr = (GLESInterop.glDepthMaskFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDepthMask"), typeof(GLESInterop.glDepthMaskFunc));
            GLESInterop.glDepthRangexPtr = (GLESInterop.glDepthRangexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDepthRangex"), typeof(GLESInterop.glDepthRangexFunc));
            GLESInterop.glDisablePtr = (GLESInterop.glDisableFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDisable"), typeof(GLESInterop.glDisableFunc));
            GLESInterop.glDisableClientStatePtr = (GLESInterop.glDisableClientStateFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDisableClientState"), typeof(GLESInterop.glDisableClientStateFunc));
            GLESInterop.glDrawArraysPtr = (GLESInterop.glDrawArraysFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDrawArrays"), typeof(GLESInterop.glDrawArraysFunc));
            GLESInterop.glDrawElementsPtr = (GLESInterop.glDrawElementsFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glDrawElements"), typeof(GLESInterop.glDrawElementsFunc));
            GLESInterop.glEnablePtr = (GLESInterop.glEnableFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glEnable"), typeof(GLESInterop.glEnableFunc));
            GLESInterop.glEnableClientStatePtr = (GLESInterop.glEnableClientStateFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glEnableClientState"), typeof(GLESInterop.glEnableClientStateFunc));
            GLESInterop.glFinishPtr = (GLESInterop.glFinishFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFinish"), typeof(GLESInterop.glFinishFunc));
            GLESInterop.glFlushPtr = (GLESInterop.glFlushFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFlush"), typeof(GLESInterop.glFlushFunc));
            GLESInterop.glFogxPtr = (GLESInterop.glFogxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFogx"), typeof(GLESInterop.glFogxFunc));
            GLESInterop.glFogxvPtr = (GLESInterop.glFogxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFogxv"), typeof(GLESInterop.glFogxvFunc));
            GLESInterop.glFrontFacePtr = (GLESInterop.glFrontFaceFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFrontFace"), typeof(GLESInterop.glFrontFaceFunc));
            GLESInterop.glFrustumxPtr = (GLESInterop.glFrustumxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glFrustumx"), typeof(GLESInterop.glFrustumxFunc));
            GLESInterop.glGetBooleanvPtr = (GLESInterop.glGetBooleanvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetBooleanv"), typeof(GLESInterop.glGetBooleanvFunc));
            GLESInterop.glGetBufferParameterivPtr = (GLESInterop.glGetBufferParameterivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetBufferParameteriv"), typeof(GLESInterop.glGetBufferParameterivFunc));
            GLESInterop.glGetClipPlanexPtr = (GLESInterop.glGetClipPlanexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetClipPlanex"), typeof(GLESInterop.glGetClipPlanexFunc));
            GLESInterop.glGenBuffersPtr = (GLESInterop.glGenBuffersFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGenBuffers"), typeof(GLESInterop.glGenBuffersFunc));
            GLESInterop.glGenTexturesPtr = (GLESInterop.glGenTexturesFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGenTextures"), typeof(GLESInterop.glGenTexturesFunc));
            GLESInterop.glGetErrorPtr = (GLESInterop.glGetErrorFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetError"), typeof(GLESInterop.glGetErrorFunc));
            GLESInterop.glGetFixedvPtr = (GLESInterop.glGetFixedvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetFixedv"), typeof(GLESInterop.glGetFixedvFunc));
            GLESInterop.glGetIntegervPtr = (GLESInterop.glGetIntegervFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetIntegerv"), typeof(GLESInterop.glGetIntegervFunc));
            GLESInterop.glGetLightxvPtr = (GLESInterop.glGetLightxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetLightxv"), typeof(GLESInterop.glGetLightxvFunc));
            GLESInterop.glGetMaterialxvPtr = (GLESInterop.glGetMaterialxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetMaterialxv"), typeof(GLESInterop.glGetMaterialxvFunc));
            GLESInterop.glGetPointervPtr = (GLESInterop.glGetPointervFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetPointerv"), typeof(GLESInterop.glGetPointervFunc));
            GLESInterop.glGetStringPtr = (GLESInterop.glGetStringFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetString"), typeof(GLESInterop.glGetStringFunc));
            GLESInterop.glGetTexEnvivPtr = (GLESInterop.glGetTexEnvivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexEnviv"), typeof(GLESInterop.glGetTexEnvivFunc));
            GLESInterop.glGetTexEnvxvPtr = (GLESInterop.glGetTexEnvxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexEnvxv"), typeof(GLESInterop.glGetTexEnvxvFunc));
            GLESInterop.glGetTexParameterivPtr = (GLESInterop.glGetTexParameterivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexParameteriv"), typeof(GLESInterop.glGetTexParameterivFunc));
            GLESInterop.glGetTexParameterxvPtr = (GLESInterop.glGetTexParameterxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glGetTexParameterxv"), typeof(GLESInterop.glGetTexParameterxvFunc));
            GLESInterop.glHintPtr = (GLESInterop.glHintFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glHint"), typeof(GLESInterop.glHintFunc));
            GLESInterop.glIsBufferPtr = (GLESInterop.glIsBufferFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glIsBuffer"), typeof(GLESInterop.glIsBufferFunc));
            GLESInterop.glIsEnabledPtr = (GLESInterop.glIsEnabledFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glIsEnabled"), typeof(GLESInterop.glIsEnabledFunc));
            GLESInterop.glIsTexturePtr = (GLESInterop.glIsTextureFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glIsTexture"), typeof(GLESInterop.glIsTextureFunc));
            GLESInterop.glLightModelxPtr = (GLESInterop.glLightModelxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightModelx"), typeof(GLESInterop.glLightModelxFunc));
            GLESInterop.glLightModelxvPtr = (GLESInterop.glLightModelxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightModelxv"), typeof(GLESInterop.glLightModelxvFunc));
            GLESInterop.glLightxPtr = (GLESInterop.glLightxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightx"), typeof(GLESInterop.glLightxFunc));
            GLESInterop.glLightxvPtr = (GLESInterop.glLightxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLightxv"), typeof(GLESInterop.glLightxvFunc));
            GLESInterop.glLineWidthxPtr = (GLESInterop.glLineWidthxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLineWidthx"), typeof(GLESInterop.glLineWidthxFunc));
            GLESInterop.glLoadIdentityPtr = (GLESInterop.glLoadIdentityFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLoadIdentity"), typeof(GLESInterop.glLoadIdentityFunc));
            GLESInterop.glLoadMatrixxPtr = (GLESInterop.glLoadMatrixxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLoadMatrixx"), typeof(GLESInterop.glLoadMatrixxFunc));
            GLESInterop.glLogicOpPtr = (GLESInterop.glLogicOpFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glLogicOp"), typeof(GLESInterop.glLogicOpFunc));
            GLESInterop.glMaterialxPtr = (GLESInterop.glMaterialxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMaterialx"), typeof(GLESInterop.glMaterialxFunc));
            GLESInterop.glMaterialxvPtr = (GLESInterop.glMaterialxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMaterialxv"), typeof(GLESInterop.glMaterialxvFunc));
            GLESInterop.glMatrixModePtr = (GLESInterop.glMatrixModeFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMatrixMode"), typeof(GLESInterop.glMatrixModeFunc));
            GLESInterop.glMultMatrixxPtr = (GLESInterop.glMultMatrixxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMultMatrixx"), typeof(GLESInterop.glMultMatrixxFunc));
            GLESInterop.glMultiTexCoord4xPtr = (GLESInterop.glMultiTexCoord4xFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glMultiTexCoord4x"), typeof(GLESInterop.glMultiTexCoord4xFunc));
            GLESInterop.glNormal3xPtr = (GLESInterop.glNormal3xFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glNormal3x"), typeof(GLESInterop.glNormal3xFunc));
            GLESInterop.glNormalPointerPtr = (GLESInterop.glNormalPointerFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glNormalPointer"), typeof(GLESInterop.glNormalPointerFunc));
            GLESInterop.glOrthoxPtr = (GLESInterop.glOrthoxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glOrthox"), typeof(GLESInterop.glOrthoxFunc));
            GLESInterop.glPixelStoreiPtr = (GLESInterop.glPixelStoreiFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPixelStorei"), typeof(GLESInterop.glPixelStoreiFunc));
            GLESInterop.glPointParameterxPtr = (GLESInterop.glPointParameterxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointParameterx"), typeof(GLESInterop.glPointParameterxFunc));
            GLESInterop.glPointParameterxvPtr = (GLESInterop.glPointParameterxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointParameterxv"), typeof(GLESInterop.glPointParameterxvFunc));
            GLESInterop.glPointSizexPtr = (GLESInterop.glPointSizexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPointSizex"), typeof(GLESInterop.glPointSizexFunc));
            GLESInterop.glPolygonOffsetxPtr = (GLESInterop.glPolygonOffsetxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPolygonOffsetx"), typeof(GLESInterop.glPolygonOffsetxFunc));
            GLESInterop.glPopMatrixPtr = (GLESInterop.glPopMatrixFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPopMatrix"), typeof(GLESInterop.glPopMatrixFunc));
            GLESInterop.glPushMatrixPtr = (GLESInterop.glPushMatrixFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glPushMatrix"), typeof(GLESInterop.glPushMatrixFunc));
            GLESInterop.glReadPixelsPtr = (GLESInterop.glReadPixelsFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glReadPixels"), typeof(GLESInterop.glReadPixelsFunc));
            GLESInterop.glRotatexPtr = (GLESInterop.glRotatexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glRotatex"), typeof(GLESInterop.glRotatexFunc));
            GLESInterop.glSampleCoveragePtr = (GLESInterop.glSampleCoverageFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glSampleCoverage"), typeof(GLESInterop.glSampleCoverageFunc));
            GLESInterop.glSampleCoveragexPtr = (GLESInterop.glSampleCoveragexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glSampleCoveragex"), typeof(GLESInterop.glSampleCoveragexFunc));
            GLESInterop.glScalexPtr = (GLESInterop.glScalexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glScalex"), typeof(GLESInterop.glScalexFunc));
            GLESInterop.glScissorPtr = (GLESInterop.glScissorFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glScissor"), typeof(GLESInterop.glScissorFunc));
            GLESInterop.glShadeModelPtr = (GLESInterop.glShadeModelFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glShadeModel"), typeof(GLESInterop.glShadeModelFunc));
            GLESInterop.glStencilFuncPtr = (GLESInterop.glStencilFuncFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glStencilFunc"), typeof(GLESInterop.glStencilFuncFunc));
            GLESInterop.glStencilMaskPtr = (GLESInterop.glStencilMaskFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glStencilMask"), typeof(GLESInterop.glStencilMaskFunc));
            GLESInterop.glStencilOpPtr = (GLESInterop.glStencilOpFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glStencilOp"), typeof(GLESInterop.glStencilOpFunc));
            GLESInterop.glTexCoordPointerPtr = (GLESInterop.glTexCoordPointerFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexCoordPointer"), typeof(GLESInterop.glTexCoordPointerFunc));
            GLESInterop.glTexEnviPtr = (GLESInterop.glTexEnviFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvi"), typeof(GLESInterop.glTexEnviFunc));
            GLESInterop.glTexEnvxPtr = (GLESInterop.glTexEnvxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvx"), typeof(GLESInterop.glTexEnvxFunc));
            GLESInterop.glTexEnvivPtr = (GLESInterop.glTexEnvivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnviv"), typeof(GLESInterop.glTexEnvivFunc));
            GLESInterop.glTexEnvxvPtr = (GLESInterop.glTexEnvxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexEnvxv"), typeof(GLESInterop.glTexEnvxvFunc));
            GLESInterop.glTexImage2DPtr = (GLESInterop.glTexImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexImage2D"), typeof(GLESInterop.glTexImage2DFunc));
            GLESInterop.glTexParameteriPtr = (GLESInterop.glTexParameteriFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameteri"), typeof(GLESInterop.glTexParameteriFunc));
            GLESInterop.glTexParameterxPtr = (GLESInterop.glTexParameterxFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameterx"), typeof(GLESInterop.glTexParameterxFunc));
            GLESInterop.glTexParameterivPtr = (GLESInterop.glTexParameterivFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameteriv"), typeof(GLESInterop.glTexParameterivFunc));
            GLESInterop.glTexParameterxvPtr = (GLESInterop.glTexParameterxvFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexParameterxv"), typeof(GLESInterop.glTexParameterxvFunc));
            GLESInterop.glTexSubImage2DPtr = (GLESInterop.glTexSubImage2DFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTexSubImage2D"), typeof(GLESInterop.glTexSubImage2DFunc));
            GLESInterop.glTranslatexPtr = (GLESInterop.glTranslatexFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glTranslatex"), typeof(GLESInterop.glTranslatexFunc));
            GLESInterop.glVertexPointerPtr = (GLESInterop.glVertexPointerFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glVertexPointer"), typeof(GLESInterop.glVertexPointerFunc));
            GLESInterop.glViewportPtr = (GLESInterop.glViewportFunc)Marshal.GetDelegateForFunctionPointer(GetProcAddress("glViewport"), typeof(GLESInterop.glViewportFunc));
        }

        public static void LoadFunction(string name)
        {
            var memberInfo = typeof(GLESInterop).GetField(name + "Ptr", BindingFlags.NonPublic | BindingFlags.Static);
            memberInfo.SetValue(null, Marshal.GetDelegateForFunctionPointer(GetProcAddress(name), memberInfo.FieldType));
        }
        #endregion
    }
}
